# SPDX-License-Identifier: Apache-2.0
# Generated by measurements/st_prefill_phase2_20260913/generate_m64_bodies.py.
# Static source fork: SFA geometry and Q1 M64 byte coordinates; see generator pins.
from __future__ import annotations

from ._moe_dynamic.gated import load_shared_bf16x8_to_f32x8
from flashinfer.cute_dsl.fp4_common import st_shared_u8
from functools import lru_cache
import hashlib
from pathlib import Path
import cuda.bindings.driver as cuda
import cutlass
import cutlass.cute as cute
import cutlass.pipeline as pipeline
import cutlass.utils as utils
import cutlass.utils.blockscaled_layout as blockscaled_utils
from cutlass.cutlass_dsl import Int32, Int64, T, dsl_user_op
from cutlass._mlir.dialects import llvm
from cutlass.cute.nvgpu import cpasync
from flashinfer.cute_dsl.fp4_common import get_ptr_as_int64, shared_ptr_to_u32
from ._moe_dynamic import gated as _stock
from ._moe_dynamic.gated import (
    DynamicLaunchParams, _TASK_SLICE_CHUNK, _ld_global_acquire_i32,
    _ld_shared_i32, _st_shared_i32,
)
from .moe_dynamic_gated_tiled import MoEGatedDynamicKernelTiled
from cutlass.cutlass_dsl import Int32, Int64, Uint8, Uint32, Uint64
from flashinfer.cute_dsl.fp4_common import (
    atomic_add_global_i32, fabs_f32, fmax_f32, rcp_approx_ftz,
    quantize_block_fp4, quantize_block_fp4_fast, get_ptr_as_int64,
    ld_shared_i32_relaxed, st_global_f32, st_global_i32,
    st_shared_i32, st_shared_f32, st_global_v4_u32, st_global_u64,
)
from ._moe_dynamic.gated import (
    DynamicLaunchParams, _TASK_SLICE_CHUNK, _ld_shared_i32, _st_shared_i32,
    _threadfence, atomic_add_shared_i32, q0_bulk_barrier_init,
    q0_cp_async_bulk, q0_bulk_arrive_expect_tx, q0_bulk_try_wait,
    load_shared_bf16x16_to_f32x16,
)
from . import moe_dynamic_gated_sf6 as _sf6
from .moe_dynamic_ep_local import MoEGatedEPLocalKernel

class M64Bodies:
    @cute.jit
    def __call__(
        self,
        a_input: cute.Tensor,  # [num_tokens, K] bf16
        topk_ids: cute.Tensor,  # [num_tokens * topk] int32
        topk_weights: cute.Tensor,  # [num_tokens * topk] float32
        packed_a: cute.Tensor,  # [rows_padded, K, 1] fp4x2 view for compute
        sfa_ptr: cute.Pointer,
        packed_a_storage: cute.Tensor,  # flat uint8 backing packed_a
        scale_storage: cute.Tensor,  # flat uint8 backing sfa_ptr
        barrier_count: cute.Tensor,  # [1] int32 (host-zeroed)
        barrier_epoch: cute.Tensor,  # [1] int32 (host-zeroed)
        pair_head: cute.Tensor,  # [1] int32
        task_head: cute.Tensor,  # [1] int32
        task_tail: cute.Tensor,  # [1] int32
        task_expert: cute.Tensor,  # [max_tasks] int32
        task_valid_rows: cute.Tensor,  # [max_tasks] int32
        b_w13: cute.Tensor,  # [2*I_tp, K, E] (gated) or [I_tp, K, E] (relu2)
        sfb_w13_ptr: cute.Pointer,  # scale factors for w13
        b_down: cute.Tensor,  # [K, I_tp, E]
        sfb_down_ptr: cute.Pointer,
        row_counts: cute.Tensor,  # expert row histogram [E]
        expert_write_rows: cute.Tensor,  # route/pack write cursors [E]
        expert_tile_base: cute.Tensor,  # compact physical-tile prefix [E + 1]
        input_global_scale: cute.Tensor,  # [E] per-expert FC1 input scale
        alpha: cute.Tensor,
        down_alpha: cute.Tensor,
        global_scale: cute.Tensor,
        scatter_output: cute.Tensor,  # [num_tokens, K]
        token_map: cute.Tensor,
        token_weights: cute.Tensor,
        sfb1_packed: cute.Tensor,
        sfb2_packed: cute.Tensor,
        max_active_clusters: cutlass.Constexpr,
        stream: cuda.CUstream,
    ):
        if cutlass.const_expr(len(b_w13.shape) == 4):
            b_w13 = cute.group_modes(b_w13, 1, 3)
        if cutlass.const_expr(len(b_down.shape) == 4):
            b_down = cute.group_modes(b_down, 1, 3)
        if cutlass.const_expr(not self.reform_sf_pack):
            MoEGatedDynamicKernelTiled.__call__(
                self, a_input, topk_ids, topk_weights, packed_a, sfa_ptr,
                packed_a_storage, scale_storage, barrier_count, barrier_epoch,
                pair_head, task_head, task_tail, task_expert, task_valid_rows,
                b_w13, sfb_w13_ptr, b_down, sfb_down_ptr, row_counts,
                expert_write_rows, expert_tile_base, input_global_scale, alpha,
                down_alpha, global_scale, scatter_output, token_map, token_weights,
                max_active_clusters, stream,
            )
        else:
            self._check_sf6_shapes(b_w13, b_down, sfb1_packed, sfb2_packed)
            self.a_dtype = packed_a.element_type
            self.b_dtype = b_w13.element_type
            self.sf_dtype = sfa_ptr.dtype
            self.a_layout = utils.LayoutEnum.from_tensor(packed_a)
            self.b_layout = utils.LayoutEnum.from_tensor(b_w13)
            # Dynamic never materializes the intermediate C tensor. Preserve the
            # original row-major epilogue layout without carrying a dead memref.
            self.c_layout = utils.LayoutEnum.ROW_MAJOR

            hidden_size = a_input.shape[1]
            if cutlass.const_expr(
                hidden_size > self.tile_shape_mnk[0] * self.tile_shape_mnk[1]
            ):
                raise ValueError(
                    "the gated dynamic kernel requires one BF16 input row to fit "
                    "in its 16384-element Q0 staging buffer"
                )
            self._setup_attributes(hidden_size=hidden_size)

            sfa_layout = blockscaled_utils.tile_atom_to_shape_SF(
                (packed_a.shape[0] * 2, packed_a.shape[1], packed_a.shape[2]), self.sf_vec_size
            )
            sfa_tensor = cute.make_tensor(sfa_ptr, sfa_layout)

            # TMA descriptors
            tma_a, gA = self._dense_cls._make_tma_atoms_and_tensors(
                packed_a,
                self.a_smem_layout_staged,
                (self.tile_shape_mnk[0], self.tile_shape_mnk[2]),
                1,
            )
            tma_sfa, gSFA = self._dense_cls._make_tma_atoms_and_tensors(
                sfa_tensor,
                self.sfa_smem_layout_staged,
                (128, self.tile_shape_mnk[2]),
                1,
                internal_type=cutlass.Int16,
            )
            # FC1 B uses a true N64 descriptor.  Each logical N128 slice is two
            # consecutive native B tiles; Up precedes Gate in global w13 storage.
            tma_b_w13, gB_w13 = self._dense_cls._make_tma_atoms_and_tensors(
                b_w13,
                self.fc1_b_smem_layout_staged,
                (self.fc1_tile_shape_mnk[1], self.fc1_tile_shape_mnk[2]),
                1,
            )
            # FC2 weight TMA; expert scales are loaded directly from SF6.
            tma_b_down, gB_down = self._dense_cls._make_tma_atoms_and_tensors(
                b_down,
                self.b_smem_layout_staged,
                (self.tile_shape_mnk[1], self.tile_shape_mnk[2]),
                1,
            )
            # W13 concatenates equally-sized Gate and Up branches along N.
            gate_tile_cnt_static = b_w13.shape[0] // self.tile_shape_mnk[1] // 2
            if cutlass.const_expr(gate_tile_cnt_static > _TASK_SLICE_CHUNK):
                raise ValueError(
                    "the gated dynamic kernel retains at most four intermediate "
                    "slices per task"
                )
            gate_tile_cnt = Int32(gate_tile_cnt_static)
            launch_params = DynamicLaunchParams(row_counts, gate_tile_cnt)
            grid = (*self.cluster_shape_mn, max_active_clusters)
            self.kernel(
                a_input,
                topk_ids,
                topk_weights,
                packed_a_storage,
                scale_storage,
                barrier_count,
                barrier_epoch,
                pair_head,
                task_head,
                task_tail,
                task_expert,
                task_valid_rows,
                tma_a,
                gA,
                tma_sfa,
                gSFA,
                tma_b_w13,
                gB_w13,
                sfb1_packed,
                tma_b_down,
                gB_down,
                sfb2_packed,
                self.tiled_mma,
                self.fc1_tiled_mma,
                self.mma_atom,
                self.mma_atom,
                self.cta_layout_mnk,
                self.a_smem_layout_staged,
                self.b_smem_layout_staged,
                self.phase2_b_smem_layout_staged,
                self.fc1_b_smem_layout_staged,
                self.sfa_smem_layout_staged,
                self.sfb_smem_layout_staged,
                self.phase2_sfb_smem_layout_staged,
                self.fc1_sfb_smem_layout_staged,
                self.fc1_sfb_smem_layout_storage,
                self.epi_smem_layout_staged,
                launch_params,
                expert_write_rows,
                expert_tile_base,
                input_global_scale,
                alpha,
                down_alpha,
                global_scale,
                scatter_output,
                token_map,
                token_weights,
            ).launch(
                grid=grid,
                block=[self.threads_per_cta, 1, 1],
                cluster=[1, 1, 1],
                cooperative=True,
                stream=stream,
            )

    @cute.kernel
    def kernel(
        self,
        a_input: cute.Tensor,
        topk_ids: cute.Tensor,
        topk_weights: cute.Tensor,
        packed_a_storage: cute.Tensor,
        scale_storage: cute.Tensor,
        barrier_count: cute.Tensor,
        barrier_epoch: cute.Tensor,
        pair_head: cute.Tensor,
        task_head: cute.Tensor,
        task_tail: cute.Tensor,
        task_expert: cute.Tensor,
        task_valid_rows: cute.Tensor,
        tma_a: cute.CopyAtom,
        mA: cute.Tensor,
        tma_sfa: cute.CopyAtom,
        mSFA: cute.Tensor,
        tma_b_w13: cute.CopyAtom,
        mB_w13: cute.Tensor,
        sfb1_packed: cute.Tensor,
        tma_b_down: cute.CopyAtom,
        mB_down: cute.Tensor,
        sfb2_packed: cute.Tensor,
        tiled_mma: cute.TiledMma,
        fc1_tiled_mma: cute.TiledMma,
        mma_atom: cute.MmaAtom,
        mma_atom_tail: cute.MmaAtom,
        cta_layout_mnk: cute.Layout,
        a_smem_staged: cute.ComposedLayout,
        b_smem_staged: cute.ComposedLayout,
        phase2_b_smem_staged: cute.ComposedLayout,
        fc1_b_smem_staged: cute.ComposedLayout,
        sfa_smem_staged: cute.Layout,
        sfb_smem_staged: cute.Layout,
        phase2_sfb_smem_staged: cute.Layout,
        fc1_sfb_smem_staged: cute.Layout,
        fc1_sfb_smem_layout_storage: cute.Layout,
        epi_smem_staged: cute.ComposedLayout,
        launch_params: DynamicLaunchParams,
        expert_write_rows: cute.Tensor,
        expert_tile_base: cute.Tensor,
        input_global_scale: cute.Tensor,
        alpha: cute.Tensor,
        down_alpha: cute.Tensor,
        global_scale: cute.Tensor,
        scatter_output: cute.Tensor,
        token_map: cute.Tensor,
        token_weights: cute.Tensor,
    ):
        """Kernel entry point."""
        tidx, _, _ = cute.arch.thread_idx()
        _bidx, _, bidz = cute.arch.block_idx()
        _, _, gdim_z = cute.arch.grid_dim()
        warp_idx = cute.arch.warp_idx()
        warp_idx = cute.arch.make_warp_uniform(warp_idx)
        lane_id = Int32(tidx) & Int32(31)
        is_cta_leader = Int32(1) if Int32(tidx) == Int32(0) else Int32(0)

        if warp_idx == 0:
            cpasync.prefetch_descriptor(tma_a)
            cpasync.prefetch_descriptor(tma_sfa)
            cpasync.prefetch_descriptor(tma_b_w13)
            cpasync.prefetch_descriptor(tma_b_down)

        cta_rank = cute.arch.make_warp_uniform(cute.arch.block_idx_in_cluster())
        cluster_coord = cta_layout_mnk.get_flat_coord(cta_rank)

        a_smem_one = cute.slice_(a_smem_staged, (None, None, 0))
        b_smem_one = cute.slice_(b_smem_staged, (None, None, 0))
        fc1_b_smem_one = cute.slice_(fc1_b_smem_staged, (None, None, 0))
        sfa_smem_one = cute.slice_(sfa_smem_staged, (None, None, 0))
        sfb_smem_one = cute.slice_(sfb_smem_staged, (None, None, 0))
        fc1_sfb_smem_one = cute.slice_(fc1_sfb_smem_staged, (None, None, 0))
        sequential_branch_compact = cutlass.const_expr(
            getattr(self, "sequential_branch_compact", False)
        )
        fc1_storage_alias = cutlass.const_expr(
            getattr(self, "fc1_storage_alias", sequential_branch_compact)
        )
        fc1_tma_copy_bytes = (
            cute.size_in_bytes(self.a_dtype, a_smem_one)
            + cute.size_in_bytes(self.b_dtype, fc1_b_smem_one)
            + cute.size_in_bytes(self.sf_dtype, sfa_smem_one)
        )
        fc1_branch_tma_copy_bytes = fc1_tma_copy_bytes
        if cutlass.const_expr(not sequential_branch_compact):
            fc1_tma_copy_bytes += cute.size_in_bytes(
                self.b_dtype, fc1_b_smem_one
            )
        phase2_tma_copy_bytes = cute.size_in_bytes(
            self.b_dtype, b_smem_one
        )

        smem = cutlass.utils.SmemAllocator()

        @cute.struct
        class StorageGated:
            # ctrl layout (16 x Int32, accessed via raw shared memory PTX):
            #   [0] has_task     [4] done          [8]  expert_idx
            #   [12] m_tile_idx  [16] slice_begin   [20] slice_count
            #   [24] valid_rows  [28] batch_base
            #   [32] next_has    [36] next_done     [40] next_expert
            #   [44] next_mtile  [48] next_begin    [52] next_count
            #   [56] next_rows   [60] reserved
            ctrl: cute.struct.MemRange[cutlass.Int32, 16]
            # Startup-only route cache aliases the unused sC backing.
            route_phys_rows: cute.struct.MemRange[cutlass.Int32, 0]
            route_expert_ids: cute.struct.MemRange[cutlass.Int32, 0]
            pipeline_array: cute.struct.MemRange[cutlass.Int64, self.ab_stage * 2]
            up_pipeline_array: cute.struct.MemRange[cutlass.Int64, self.ab_stage * 2]
            phase2_pipeline_array: cute.struct.MemRange[
                cutlass.Int64, self.phase2_stage * 2
            ]
            q0_bulk_barrier: cute.struct.MemRange[cutlass.Int64, 1]
            scatter_tok_cache: cute.struct.MemRange[
                cutlass.Int32, self.tile_shape_mnk[0] * 2
            ]
            scatter_weight_cache: cute.struct.MemRange[cutlass.Float32, 0]
            sB: cute.struct.Align[
                cute.struct.MemRange[self.b_dtype, cute.cosize(b_smem_staged)],
                self.buffer_align_bytes,
            ]
            # During FC1, the first B-sized part of sC is the contiguous
            # third N128 B stage.  FC1 releases it before activation writes.
            sC: cute.struct.Align[
                cute.struct.MemRange[cutlass.BFloat16, cute.cosize(epi_smem_staged)],
                self.buffer_align_bytes,
            ]
            sA: cute.struct.Align[
                cute.struct.MemRange[self.a_dtype, cute.cosize(a_smem_staged)],
                self.buffer_align_bytes,
            ]
            # Gate and Up occupy disjoint N64 halves of the N128 sB stage.
            sB_up: cute.struct.Align[
                cute.struct.MemRange[self.b_dtype, 0],
                self.buffer_align_bytes,
            ]
            sSFA: cute.struct.Align[
                cute.struct.MemRange[self.sf_dtype, cute.cosize(sfa_smem_staged)],
                self.buffer_align_bytes,
            ]
            sSFB: cute.struct.Align[
                cute.struct.MemRange[self.sf_dtype, cute.cosize(sfb_smem_staged)],
                self.buffer_align_bytes,
            ]
            sSFB_phase2_extra: cute.struct.Align[
                cute.struct.MemRange[self.sf_dtype, cute.cosize(sfb_smem_one)],
                self.buffer_align_bytes,
            ]
            # SM120 packs each logical N64 SFB half in a physical-N128 block;
            # the Up branch therefore needs a distinct physical backing.
            sSFB_up: cute.struct.Align[
                cute.struct.MemRange[
                    self.sf_dtype,
                    (
                        0
                        if fc1_storage_alias
                        else cute.cosize(fc1_sfb_smem_layout_storage)
                    ),
                ],
                self.buffer_align_bytes,
            ]

        storage = smem.allocate(StorageGated)

        prod_group = pipeline.CooperativeGroup(pipeline.Agent.Thread)
        cons_group = pipeline.CooperativeGroup(
            pipeline.Agent.Thread, self.num_mma_warps
        )
        cta_layout_vmnk = cute.make_layout((1, *cta_layout_mnk.shape))
        ml_pipeline = pipeline.PipelineTmaAsync.create(
            num_stages=self.ab_stage,
            producer_group=prod_group,
            consumer_group=cons_group,
            tx_count=fc1_tma_copy_bytes,
            barrier_storage=storage.pipeline_array.data_ptr(),
            cta_layout_vmnk=cta_layout_vmnk,
        )
        up_pipeline = pipeline.PipelineTmaAsync.create(
            num_stages=self.ab_stage,
            producer_group=prod_group,
            consumer_group=cons_group,
            tx_count=fc1_branch_tma_copy_bytes,
            barrier_storage=storage.up_pipeline_array.data_ptr(),
            cta_layout_vmnk=cta_layout_vmnk,
        )
        phase2_pipeline = pipeline.PipelineTmaAsync.create(
            num_stages=self.phase2_stage,
            producer_group=prod_group,
            consumer_group=cons_group,
            tx_count=phase2_tma_copy_bytes,
            barrier_storage=storage.phase2_pipeline_array.data_ptr(),
            cta_layout_vmnk=cta_layout_vmnk,
        )

        cute.arch.sync_threads()

        sA = storage.sA.get_tensor(a_smem_staged.outer, swizzle=a_smem_staged.inner)
        sB = storage.sB.get_tensor(b_smem_staged.outer, swizzle=b_smem_staged.inner)
        # FC2 retains its two physical B stages and addresses dead sA[0]
        # separately as phase2 stage2.  Conversely FC1 sees one contiguous
        # three-stage N128 backing spanning sB[0:2] and the beginning of sC.
        phase2_b_extra_ptr = cute.recast_ptr(
            storage.sA.data_ptr(),
            b_smem_one.inner,
            dtype=self.b_dtype,
        )
        sB_phase2_extra = cute.make_tensor(phase2_b_extra_ptr, b_smem_one.outer)
        sB_fc1_all = storage.sB.get_tensor(
            phase2_b_smem_staged.outer,
            swizzle=phase2_b_smem_staged.inner,
        )
        # While FC1 is live, split the N128 FC2 backing into two N64 views.
        sB_fc1 = cute.local_tile(
            sB_fc1_all,
            cute.slice_(self.fc1_tile_shape_mnk, (0, None, None)),
            (0, 0, None),
        )
        sB_up_fc1 = cute.local_tile(
            sB_fc1_all,
            cute.slice_(self.fc1_tile_shape_mnk, (0, None, None)),
            (1, 0, None),
        )
        sSFA = storage.sSFA.get_tensor(sfa_smem_staged)
        sSFB = storage.sSFB.get_tensor(sfb_smem_staged)
        # sSFB_phase2_extra is the immediately following aligned field, so
        # expose the existing two-plus-one backing as one staged tensor.
        sSFB_phase2 = storage.sSFB.get_tensor(phase2_sfb_smem_staged)
        # Gate gets a contiguous third SFB stage from the existing phase2
        # extra.  Up keeps its two allocated stages and uses a disjoint
        # one-stage alias in sC immediately after the FC1 B-stage2 bytes.
        sSFB_fc1 = storage.sSFB.get_tensor(fc1_sfb_smem_staged)
        sSFB_up_fc1 = (
            sSFB_fc1
            if fc1_storage_alias
            else storage.sSFB_up.get_tensor(fc1_sfb_smem_layout_storage)
        )
        fc1_sfb_smem_one = cute.slice_(fc1_sfb_smem_staged, (None, None, 0))
        fc1_b_stage_bytes = cute.size_in_bytes(self.b_dtype, b_smem_one)
        sSFB_up_fc1_extra_ptr = cute.recast_ptr(
            storage.sC.data_ptr() + fc1_b_stage_bytes // 2,
            dtype=self.sf_dtype,
        )
        sSFB_up_fc1_extra = cute.make_tensor(sSFB_up_fc1_extra_ptr, fc1_sfb_smem_one)
        sC = storage.sC.get_tensor(
            epi_smem_staged.outer,
            swizzle=epi_smem_staged.inner,
        )
        sfa_base_addr = shared_ptr_to_u32(storage.sSFA.data_ptr())
        sfa_stage_elements = Int32(cute.cosize(sfa_smem_one))
        ctrl_base_addr = shared_ptr_to_u32(storage.ctrl.data_ptr())
        # Q0 uses raw-linear sC as an eight-token BF16 staging buffer.
        # Move both 288-entry route caches to startup-idle sA.
        route_phys_rows_addr = shared_ptr_to_u32(storage.sA.data_ptr())
        route_expert_ids_addr = route_phys_rows_addr + Int32(
            (self.num_mma_warps + 1) * 32 * 4
        )
        q0_input_stage_base_addr = shared_ptr_to_u32(storage.sC.data_ptr())
        q0_bulk_barrier_addr = shared_ptr_to_u32(storage.q0_bulk_barrier.data_ptr())
        scatter_tok_base_addr = shared_ptr_to_u32(storage.scatter_tok_cache.data_ptr())
        scatter_weight_base_addr = scatter_tok_base_addr + Int32(4)

        self.initialize_route_q0_and_publish(
            (tidx, bidz, gdim_z, warp_idx, is_cta_leader),
            (a_input, topk_ids, topk_weights, input_global_scale),
            (
                packed_a_storage,
                scale_storage,
                scatter_output,
                token_map,
                token_weights,
            ),
            (expert_write_rows, expert_tile_base, pair_head),
            (
                task_head,
                task_tail,
                task_expert,
                task_valid_rows,
            ),
            (barrier_count, barrier_epoch),
            (
                ctrl_base_addr,
                route_phys_rows_addr,
                route_expert_ids_addr,
                q0_input_stage_base_addr,
                q0_bulk_barrier_addr,
            ),
            launch_params,
        )

        # Deferred publication is complete after the resident-grid barrier
        # inside initialize_route_q0_and_publish.  Cache the immutable tail in
        # the otherwise streaming-only ctrl[28] slot; the claim loop uses a
        # side-effecting shared load to preserve phase ordering.
        if is_cta_leader > Int32(0):
            stable_task_tail = _ld_global_acquire_i32(
                get_ptr_as_int64(task_tail, Int32(0))
            )
            _st_shared_i32(ctrl_base_addr + Int32(28), stable_task_tail)
            _st_shared_i32(ctrl_base_addr + Int32(32), Int32(0))
            _st_shared_i32(ctrl_base_addr + Int32(36), Int32(0))

        gA = cute.local_tile(
            mA, cute.slice_(self.tile_shape_mnk, (None, 0, None)), (None, None, None)
        )
        # B is tiled at the native N64 compute granularity.  SFB is tiled at
        # the physical N128 scale-factor block granularity and replayed for
        # the two B halves.
        gB_w13_tiled = cute.local_tile(
            mB_w13,
            cute.slice_(self.fc1_tile_shape_mnk, (0, None, None)),
            (None, None, None),
        )
        gSFA = cute.local_tile(
            mSFA, (128, self.tile_shape_mnk[2]), (None, None, None)
        )
        thr_mma = tiled_mma.get_slice(tidx)
        fc1_thr_mma = fc1_tiled_mma.get_slice(tidx)

        a_cta_layout = cute.make_layout(cute.slice_(cta_layout_mnk, (0, None, 0)).shape)
        a_cta_crd = cluster_coord[1]
        b_cta_layout = cute.make_layout(cute.slice_(cta_layout_mnk, (None, 0, 0)).shape)
        b_cta_crd = cluster_coord[0]

        tAsA, tAgA = cpasync.tma_partition(
            tma_a,
            a_cta_crd,
            a_cta_layout,
            cute.group_modes(sA, 0, 2),
            cute.group_modes(gA, 0, 2),
        )
        tAsSFA, tAgSFA = cpasync.tma_partition(
            tma_sfa,
            a_cta_crd,
            a_cta_layout,
            cute.group_modes(sSFA, 0, 2),
            cute.group_modes(gSFA, 0, 2),
        )
        tAsSFA = cute.filter_zeros(tAsSFA)
        tAgSFA = cute.filter_zeros(tAgSFA)

        # w13 FC1 partitions: N64 B payload plus physical-N128 SFB payload.
        tBsB_w13, tBgB_w13 = cpasync.tma_partition(
            tma_b_w13,
            b_cta_crd,
            b_cta_layout,
            cute.group_modes(sB_fc1, 0, 2),
            cute.group_modes(gB_w13_tiled, 0, 2),
        )
        tBsB_w13_up, _tBgB_w13_up = cpasync.tma_partition(
            tma_b_w13,
            b_cta_crd,
            b_cta_layout,
            cute.group_modes(sB_up_fc1, 0, 2),
            cute.group_modes(gB_w13_tiled, 0, 2),
        )
        # Existing raw shared layouts remain consumer-owned stage storage.
        # Only their producer changes; no raw global scale descriptor exists.
        tBsSFB_w13, tBgSFB_w13 = sSFB_fc1, sfb1_packed
        tBsSFB_w13_up = sSFB_up_fc1
        tBsSFB_w13_up_extra = sSFB_up_fc1_extra

        # B_down TMA partitions
        gB_down = cute.local_tile(
            mB_down,
            cute.slice_(self.tile_shape_mnk, (0, None, None)),
            (None, None, None),
        )
        tBsB_down, tBgB_down = cpasync.tma_partition(
            tma_b_down,
            b_cta_crd,
            b_cta_layout,
            cute.group_modes(sB, 0, 2),
            cute.group_modes(gB_down, 0, 2),
        )
        tBsB_down_extra, _tBgB_down_extra = cpasync.tma_partition(
            tma_b_down,
            b_cta_crd,
            b_cta_layout,
            cute.group_modes(sB_phase2_extra, 0, 2),
            cute.group_modes(gB_down, 0, 2),
        )
        tBsSFB_down, tBgSFB_down = sSFB_phase2, sfb2_packed

        # FC2 fragment partitions retain the original N128 contract.
        tCsA = thr_mma.partition_A(sA)
        tCrA = tiled_mma.make_fragment_A(tCsA[None, None, None, 0])
        tCrSFA = self._dense_cls._partition_fragment_SFA(
            self,  # type: ignore[arg-type]
            sSFA[None, None, 0],
            thr_mma,
            tidx,
        )

        # FC1 has an independent N64 MMA/permutation and aliases the same A/SFA
        # storage.  Its SFB fragment is created per half below because a
        # physical N128 SFB block contains two logical N64 scale tiles.
        tCsA_fc1 = fc1_thr_mma.partition_A(sA)
        tCrA_fc1 = fc1_tiled_mma.make_fragment_A(tCsA_fc1[None, None, None, 0])
        tCrSFA_fc1 = self._dense_cls._partition_fragment_SFA(
            self,  # type: ignore[arg-type]
            sSFA[None, None, 0],
            fc1_thr_mma,
            tidx,
        )
        tCsB_fc1 = fc1_thr_mma.partition_B(sB_fc1)
        tCrB_fc1 = fc1_tiled_mma.make_fragment_B(tCsB_fc1[None, None, None, 0])
        tCsB_up_fc1 = fc1_thr_mma.partition_B(sB_up_fc1)
        tCrB_up_fc1 = fc1_tiled_mma.make_fragment_B(tCsB_up_fc1[None, None, None, 0])
        tCsB = thr_mma.partition_B(sB)
        tCrB = tiled_mma.make_fragment_B(tCsB[None, None, None, 0])
        tCrSFB = self._dense_cls._partition_fragment_SFB(
            self,  # type: ignore[arg-type]
            sSFB[None, None, 0],
            thr_mma,
            tidx,
        )

        tCsC_for_shape = thr_mma.partition_C(sC[None, None, 0])
        epi_m_scale = self.tile_shape_mnk[0] // self.epi_tile[0]
        sub_shape = tCsC_for_shape.shape[:3]
        acc_shape = (sub_shape[0], sub_shape[1] * epi_m_scale, sub_shape[2])
        k_tile_cnt = cute.size(gA, mode=[3])
        fc1_k_tile_cnt = k_tile_cnt
        # gB is native-N64 while tasks and FC2 remain logical-N128.
        native_fc1_tile_cnt = cute.size(gB_w13_tiled, mode=[2]) // Int32(2)
        gate_tile_cnt = native_fc1_tile_cnt // Int32(2)
        output_tile_cnt = cute.size(gB_down, mode=[2])

        prod_state = pipeline.make_pipeline_state(
            pipeline.PipelineUserType.Producer, self.ab_stage
        )
        cons_state = pipeline.make_pipeline_state(
            pipeline.PipelineUserType.Consumer, self.ab_stage
        )
        up_prod_state = pipeline.make_pipeline_state(
            pipeline.PipelineUserType.Producer, self.ab_stage
        )
        up_cons_state = pipeline.make_pipeline_state(
            pipeline.PipelineUserType.Consumer, self.ab_stage
        )
        phase2_prod_state = pipeline.make_pipeline_state(
            pipeline.PipelineUserType.Producer, self.phase2_stage
        )
        phase2_cons_state = pipeline.make_pipeline_state(
            pipeline.PipelineUserType.Consumer, self.phase2_stage
        )

        num_k_blocks = cute.size(tCrA, mode=[2])
        fc1_num_k_blocks = cute.size(tCrA_fc1, mode=[2])

        atom_ld_A = cute.make_copy_atom(
            cute.nvgpu.warp.LdMatrix8x8x16bOp(self.a_layout.is_m_major_a(), 4),
            self.a_dtype,
        )
        atom_ld_B = cute.make_copy_atom(
            cute.nvgpu.warp.LdMatrix8x8x16bOp(self.b_layout.is_n_major_b(), 4),
            self.b_dtype,
        )
        smem_copy_A = cute.make_tiled_copy_A(atom_ld_A, tiled_mma)
        smem_copy_B = cute.make_tiled_copy_B(atom_ld_B, tiled_mma)
        atom_ld_SF = cute.make_copy_atom(cute.nvgpu.CopyUniversalOp(), self.sf_dtype)
        smem_copy_SFA = cute.make_tiled_copy(
            atom_ld_SF,
            self._dense_cls._get_layoutSFA_TV(self, tiled_mma),  # type: ignore[arg-type]
            (
                cute.size(tiled_mma.permutation_mnk[0]),
                cute.size(tiled_mma.permutation_mnk[2]),
            ),
        )
        smem_copy_SFB = cute.make_tiled_copy(
            atom_ld_SF,
            self._dense_cls._get_layoutSFB_TV(self, tiled_mma),  # type: ignore[arg-type]
            (
                cute.size(tiled_mma.permutation_mnk[1]),
                cute.size(tiled_mma.permutation_mnk[2]),
            ),
        )
        smem_copy_A_fc1 = cute.make_tiled_copy_A(atom_ld_A, fc1_tiled_mma)
        smem_copy_B_fc1 = cute.make_tiled_copy_B(atom_ld_B, fc1_tiled_mma)
        smem_copy_SFA_fc1 = cute.make_tiled_copy(
            atom_ld_SF,
            self._dense_cls._get_layoutSFA_TV(self, fc1_tiled_mma),  # type: ignore[arg-type]
            (
                cute.size(fc1_tiled_mma.permutation_mnk[0]),
                cute.size(fc1_tiled_mma.permutation_mnk[2]),
            ),
        )
        smem_copy_SFB_fc1 = cute.make_tiled_copy(
            atom_ld_SF,
            self._dense_cls._get_layoutSFB_TV(self, fc1_tiled_mma),  # type: ignore[arg-type]
            (
                cute.size(fc1_tiled_mma.permutation_mnk[1]),
                cute.size(fc1_tiled_mma.permutation_mnk[2]),
            ),
        )

        thr_ld_A = smem_copy_A.get_slice(tidx)
        thr_ld_B = smem_copy_B.get_slice(tidx)
        csA = thr_ld_A.partition_S(sA)
        crA = thr_ld_A.retile(tCrA)
        csB = thr_ld_B.partition_S(sB)
        csB_phase2_extra = thr_ld_B.partition_S(sB_phase2_extra)
        crB = thr_ld_B.retile(tCrB)

        thr_ld_SFA = smem_copy_SFA.get_slice(tidx)
        thr_ld_SFB = smem_copy_SFB.get_slice(tidx)
        csSFA = thr_ld_SFA.partition_S(sSFA)
        crSFA = thr_ld_SFA.retile(tCrSFA)
        csSFB = thr_ld_SFB.partition_S(sSFB_phase2)
        crSFB = thr_ld_SFB.retile(tCrSFB)

        thr_ld_A_fc1 = smem_copy_A_fc1.get_slice(tidx)
        thr_ld_B_fc1 = smem_copy_B_fc1.get_slice(tidx)
        csA_fc1 = thr_ld_A_fc1.partition_S(sA)
        crA_fc1 = thr_ld_A_fc1.retile(tCrA_fc1)
        csB_fc1 = thr_ld_B_fc1.partition_S(sB_fc1)
        crB_fc1 = thr_ld_B_fc1.retile(tCrB_fc1)
        csB_up_fc1 = thr_ld_B_fc1.partition_S(sB_up_fc1)
        crB_up_fc1 = thr_ld_B_fc1.retile(tCrB_up_fc1)

        thr_ld_SFA_fc1 = smem_copy_SFA_fc1.get_slice(tidx)
        thr_ld_SFB_fc1 = smem_copy_SFB_fc1.get_slice(tidx)
        csSFA_fc1 = thr_ld_SFA_fc1.partition_S(sSFA)
        crSFA_fc1 = thr_ld_SFA_fc1.retile(tCrSFA_fc1)

        # ===================================================================
        # Per-warp setup for the consumer steady state
        # ===================================================================
        if warp_idx < self.num_mma_warps:
            cute.arch.setmaxregister_increase(self.mma_register_requirement)
        elif warp_idx == self.tma_load_warp_id:
            cute.arch.setmaxregister_decrease(self.load_register_requirement)

        # ===================================================================
        # Consumer steady state: pop one ready task per CTA, then let
        # the MMA warps and DMA warp cooperate on that task.
        # ===================================================================
        consumer_live = Int32(1)
        while consumer_live > Int32(0):
            has_task, is_done = self.claim_and_cache_task(
                tidx,
                warp_idx,
                is_cta_leader,
                ctrl_base_addr,
                task_head,
                task_expert,
                task_valid_rows,
                token_map,
                token_weights,
                scatter_tok_base_addr,
                scatter_weight_base_addr,
            )
            if has_task == Int32(0):
                if is_done > Int32(0):
                    consumer_live = Int32(0)
            elif warp_idx < self.num_mma_warps:
                task_expert_idx = _ld_shared_i32(ctrl_base_addr + Int32(8))
                task_m_tile_idx = _ld_shared_i32(ctrl_base_addr + Int32(12))
                task_slice_begin_idx = _ld_shared_i32(ctrl_base_addr + Int32(16))
                task_slice_count_val = _ld_shared_i32(ctrl_base_addr + Int32(20))
                task_valid_rows_val = _ld_shared_i32(ctrl_base_addr + Int32(24))

                alpha_value = alpha[task_expert_idx].to(cutlass.Float32)
                valid_rows = task_valid_rows_val
                # atom_layout=(4,2,1): two M16 fragments per warp, separated
                # by 64 rows. Full tasks use the original branch-free method.
                warp_m_coord = Int32(warp_idx) & Int32(3)

                _is_m_major = self.c_layout.is_m_major_c()
                copy_atom_r2s = cute.make_copy_atom(
                    cute.nvgpu.CopyUniversalOp(),
                    cutlass.BFloat16,
                )
                copy_atom_C = cute.make_copy_atom(
                    cute.nvgpu.warp.StMatrix8x8x16bOp(_is_m_major, 2),
                    cutlass.BFloat16,
                )
                tiled_copy_C_Atom = cute.make_tiled_copy_C_atom(copy_atom_C, tiled_mma)
                tiled_copy_r2s = cute.make_tiled_copy_S(
                    copy_atom_r2s, tiled_copy_C_Atom
                )
                fc1_tiled_copy_C_Atom = cute.make_tiled_copy_C_atom(
                    copy_atom_C, fc1_tiled_mma
                )
                fc1_tiled_copy_r2s = cute.make_tiled_copy_S(
                    copy_atom_r2s, fc1_tiled_copy_C_Atom
                )

                thr_copy_r2s = tiled_copy_r2s.get_slice(tidx)
                tRS_sD = thr_copy_r2s.partition_D(sC)
                fc1_thr_copy_r2s = fc1_tiled_copy_r2s.get_slice(tidx)
                fc1_tRS_sD = fc1_thr_copy_r2s.partition_D(sC)
                down_alpha_value = down_alpha[task_expert_idx].to(cutlass.Float32)
                epi_rest_m = self.tile_shape_mnk[0] // self.epi_tile[0]

                fc1_m_tiles = cute.size(tCrA_fc1, mode=[1])
                fc1_n_tiles = cute.size(tCrB_fc1, mode=[1])
                deferred_a_words = cute.make_rmem_tensor((8,), cutlass.Uint32)
                deferred_a_words.fill(0)
                deferred_sfa_words = cute.make_rmem_tensor((2,), cutlass.Uint32)
                deferred_sfa_words.fill(0)
                slice_idx = Int32(0)
                while slice_idx < task_slice_count_val:
                    if valid_rows == Int32(self.tile_shape_mnk[0]):
                        cons_state, up_cons_state = self.fc1_gate_up_swiglu_to_sC(
                            tidx,
                            ml_pipeline,
                            cons_state,
                            up_pipeline,
                            up_cons_state,
                            fc1_tiled_mma,
                            mma_atom,
                            sSFB_fc1,
                            sSFB_up_fc1,
                            sSFB_up_fc1_extra,
                            fc1_thr_mma,
                            thr_ld_SFB_fc1,
                            csA_fc1,
                            csB_fc1,
                            csB_up_fc1,
                            csSFA_fc1,
                            crA_fc1,
                            crB_fc1,
                            crB_up_fc1,
                            crSFA_fc1,
                            tCrA_fc1,
                            tCrB_fc1,
                            tCrB_up_fc1,
                            tCrSFA_fc1,
                            smem_copy_A_fc1,
                            smem_copy_B_fc1,
                            smem_copy_SFA_fc1,
                            smem_copy_SFB_fc1,
                            fc1_tiled_copy_r2s,
                            fc1_tRS_sD,
                            fc1_k_tile_cnt,
                            fc1_num_k_blocks,
                            fc1_m_tiles,
                            fc1_n_tiles,
                            alpha_value,
                            valid_rows,
                            task_expert_idx,
                            global_scale,
                            sC,
                            sA,
                            sfa_base_addr,
                            epi_rest_m,
                        )
                    else:
                        cons_state, up_cons_state = self.fc1_gate_up_swiglu_to_sC_tail(
                            tidx,
                            ml_pipeline,
                            cons_state,
                            up_pipeline,
                            up_cons_state,
                            fc1_tiled_mma,
                            mma_atom_tail,
                            sSFB_fc1,
                            sSFB_up_fc1,
                            sSFB_up_fc1_extra,
                            fc1_thr_mma,
                            thr_ld_SFB_fc1,
                            csA_fc1,
                            csB_fc1,
                            csB_up_fc1,
                            csSFA_fc1,
                            crA_fc1,
                            crB_fc1,
                            crB_up_fc1,
                            crSFA_fc1,
                            tCrA_fc1,
                            tCrB_fc1,
                            tCrB_up_fc1,
                            tCrSFA_fc1,
                            smem_copy_A_fc1,
                            smem_copy_B_fc1,
                            smem_copy_SFA_fc1,
                            smem_copy_SFB_fc1,
                            fc1_tiled_copy_r2s,
                            fc1_tRS_sD,
                            fc1_k_tile_cnt,
                            fc1_num_k_blocks,
                            fc1_m_tiles,
                            fc1_n_tiles,
                            alpha_value,
                            valid_rows,
                            warp_m_coord,
                            task_expert_idx,
                            global_scale,
                            sC,
                            sA,
                            sfa_base_addr,
                            epi_rest_m,
                        )

                    cute.arch.fence_proxy("async.shared", space="cta")
                    self.epilog_sync_barrier.arrive_and_wait()
                    q1_a_stage_idx = Int32(3)
                    defer_a = Int32(0)
                    if slice_idx == Int32(1):
                        q1_a_stage_idx = Int32(4)
                    elif slice_idx == Int32(2):
                        q1_a_stage_idx = Int32(0)
                        defer_a = Int32(1)
                    elif slice_idx == Int32(3):
                        q1_a_stage_idx = Int32(1)

                    q1_sfa_stage_idx = Int32(3)
                    defer_sfa = Int32(0)
                    deferred_sfa_slot = Int32(0)
                    if slice_idx == Int32(1):
                        q1_sfa_stage_idx = Int32(0)
                        defer_sfa = Int32(1)
                    elif slice_idx == Int32(2):
                        q1_sfa_stage_idx = Int32(0)
                        defer_sfa = Int32(1)
                        deferred_sfa_slot = Int32(1)
                    elif slice_idx == Int32(3):
                        q1_sfa_stage_idx = Int32(0)
                    self.quantize_q1_sC_to_sA_sSFA(
                        tidx,
                        valid_rows,
                        task_expert_idx,
                        global_scale,
                        sC,
                        sA,
                        fc1_tRS_sD,
                        sfa_base_addr,
                        sfa_stage_elements,
                        q1_a_stage_idx,
                        defer_a,
                        deferred_a_words,
                        q1_sfa_stage_idx,
                        defer_sfa,
                        deferred_sfa_words,
                        deferred_sfa_slot,
                        epi_rest_m,
                    )
                    cute.arch.fence_proxy("async.shared", space="cta")
                    self.epilog_sync_barrier.arrive_and_wait()
                    self.pass_gate_barrier.arrive_unaligned()

                    # Q1 has finished reading sC, so the following FC1 slice
                    # may safely reuse it as the third B/SFB stage.
                    slice_idx += Int32(1)

                # The final FC1 pass has released A/SFA stages0:2.  Materialize
                # the exact packed Q1 bytes deferred to registers.
                self.flush_deferred_q1_a(
                    tidx,
                    valid_rows,
                    deferred_a_words,
                    sA,
                    Int32(2),
                )
                self.flush_deferred_q1_sfa(
                    tidx,
                    valid_rows,
                    deferred_sfa_words[0],
                    sfa_base_addr,
                    sfa_stage_elements,
                    Int32(1),
                )
                self.flush_deferred_q1_sfa(
                    tidx,
                    valid_rows,
                    deferred_sfa_words[1],
                    sfa_base_addr,
                    sfa_stage_elements,
                    Int32(2),
                )
                self.epilog_sync_barrier.arrive_and_wait()

                phase2_cons_state.reset_count()
                for output_tile_idx in range(0, output_tile_cnt, 1, unroll=4):  # type: ignore[call-overload]
                    physical_output_tile_idx = (
                        Int32(output_tile_idx) + task_expert_idx
                    ) % Int32(output_tile_cnt)
                    down_acc = cute.make_rmem_tensor(acc_shape, self.acc_dtype)
                    down_acc.fill(0.0)
                    slice_idx = Int32(0)
                    while slice_idx < task_slice_count_val:
                        q1_a_stage_idx = Int32(3)
                        if slice_idx == Int32(1):
                            q1_a_stage_idx = Int32(4)
                        elif slice_idx == Int32(2):
                            q1_a_stage_idx = Int32(2)
                        elif slice_idx == Int32(3):
                            q1_a_stage_idx = Int32(1)

                        q1_sfa_stage_idx = Int32(3)
                        if slice_idx == Int32(1):
                            q1_sfa_stage_idx = Int32(1)
                        elif slice_idx == Int32(2):
                            q1_sfa_stage_idx = Int32(2)
                        elif slice_idx == Int32(3):
                            q1_sfa_stage_idx = Int32(0)
                        self.load_fc2_a_fragments(
                            num_k_blocks,
                            q1_a_stage_idx,
                            q1_sfa_stage_idx,
                            (csA, csSFA),
                            (crA, crSFA),
                            (smem_copy_A, smem_copy_SFA),
                        )
                        if valid_rows == Int32(self.tile_shape_mnk[0]):
                            phase2_cons_state = self.fc2_accumulate_slice(
                                num_k_blocks,
                                mma_atom,
                                down_acc,
                                (phase2_pipeline, phase2_cons_state),
                                (csB, csB_phase2_extra, csSFB),
                                (tCrA, tCrB, tCrSFA, tCrSFB, crB, crSFB),
                                (smem_copy_B, smem_copy_SFB),
                            )
                        else:
                            phase2_cons_state = self.fc2_accumulate_slice_tail(
                                num_k_blocks,
                                mma_atom_tail,
                                down_acc,
                                valid_rows,
                                warp_m_coord,
                                (phase2_pipeline, phase2_cons_state),
                                (csB, csB_phase2_extra, csSFB),
                                (tCrA, tCrB, tCrSFA, tCrSFB, crB, crSFB),
                                (smem_copy_B, smem_copy_SFB),
                            )
                        slice_idx += Int32(1)

                    self.fc2_epilogue_to_sC(
                        acc_shape,
                        down_alpha_value,
                        down_acc,
                        sC,
                        tiled_copy_r2s,
                        thr_copy_r2s,
                        tRS_sD,
                    )
                    cute.arch.fence_proxy("async.shared", space="cta")
                    if (warp_idx & Int32(2)) == Int32(0):
                        self.fc2_group_a_barrier.arrive_and_wait()
                    else:
                        self.fc2_group_b_barrier.arrive_and_wait()
                    self.scatter_sC_to_gmem(
                        tidx,
                        physical_output_tile_idx,
                        valid_rows,
                        sC,
                        tRS_sD,
                        scatter_output,
                        scatter_tok_base_addr,
                        scatter_weight_base_addr,
                        down_alpha_value,
                    )
                    if (warp_idx & Int32(2)) == Int32(0):
                        self.fc2_group_a_barrier.arrive_and_wait()
                    else:
                        self.fc2_group_b_barrier.arrive_and_wait()

                # All output tiles have consumed every retained Q1 slice.
                self.pass_final_barrier.arrive_and_wait()

            elif warp_idx == self.tma_load_warp_id:
                task_expert_idx = _ld_shared_i32(ctrl_base_addr + Int32(8))
                task_m_tile_idx = _ld_shared_i32(ctrl_base_addr + Int32(12))
                task_slice_begin_idx = _ld_shared_i32(ctrl_base_addr + Int32(16))
                task_slice_count_val = _ld_shared_i32(ctrl_base_addr + Int32(20))

                tAgA_mk = tAgA[(None, task_m_tile_idx, None, Int32(0))]
                tAgSFA_mk = tAgSFA[(None, task_m_tile_idx, None, Int32(0))]
                slice_idx = Int32(0)
                while slice_idx < task_slice_count_val:
                    intermediate_slice = task_slice_begin_idx + slice_idx
                    wait_for_prior_slice = Int32(0)
                    if slice_idx > Int32(0):
                        wait_for_prior_slice = Int32(1)
                    prod_state, up_prod_state = self.load_fc1_tma_slice(
                        intermediate_slice,
                        wait_for_prior_slice,
                        task_expert_idx,
                        gate_tile_cnt,
                        fc1_k_tile_cnt,
                        prod_state,
                        ml_pipeline,
                        up_prod_state,
                        up_pipeline,
                        (tma_a, tma_b_w13, tma_sfa),
                        (tAgA_mk, tAgSFA_mk, tBgB_w13, tBgSFB_w13),
                        (
                            tAsA,
                            tAsSFA,
                            tBsB_w13,
                            tBsB_w13_up,
                            tBsSFB_w13,
                            tBsSFB_w13_up,
                            tBsSFB_w13_up_extra,
                        ),
                    )
                    slice_idx += Int32(1)

                # The final FC1 MMA release is narrower than pass_gate:
                # clone the state so we can prove every FC1 A/B/SF stage is
                # empty without advancing the live producer state.  FC2
                # weights do not alias sC, so they may prefetch while final
                # activation/Q1 is still using sC.
                fc1_drain_state = prod_state.clone()
                ml_pipeline.producer_tail(fc1_drain_state)

                phase2_prod_state.reset_count()
                for output_tile_idx in range(0, output_tile_cnt, 1, unroll=4):  # type: ignore[call-overload]
                    physical_output_tile_idx = (
                        Int32(output_tile_idx) + task_expert_idx
                    ) % Int32(output_tile_cnt)
                    slice_idx = Int32(0)
                    while slice_idx < task_slice_count_val:
                        intermediate_slice = task_slice_begin_idx + slice_idx
                        phase2_prod_state = self.load_fc2_tma_tile(
                            intermediate_slice,
                            physical_output_tile_idx,
                            task_expert_idx,
                            phase2_prod_state,
                            phase2_pipeline,
                            (tma_b_down,),
                            (tBgB_down, tBgSFB_down),
                            (
                                tBsB_down,
                                tBsB_down_extra,
                                tBsSFB_down,
                            ),
                        )
                        slice_idx += Int32(1)

                # Warp8 has finished issuing current-task FC2 weights while
                # math warps still own FC2 MMA/epilogue/scatter. Reserve and
                # cache one next descriptor in disjoint shared control state.
                self.prefetch_next_task_descriptor(
                    lane_id,
                    ctrl_base_addr,
                    task_head,
                    task_expert,
                    task_valid_rows,
                )

                # Consume the final slice's activation/Q1 arrival before the
                # task handoff. Earlier arrivals were consumed lazily at the
                # first next-slice Stage2 overwrite.
                self.pass_gate_barrier.wait_unaligned()

                # Keep A4/Q1 and sC alive until all output tiles complete.
                self.pass_final_barrier.wait_unaligned()

        if warp_idx == self.tma_load_warp_id:
            ml_pipeline.producer_tail(prod_state)
            if cutlass.const_expr(getattr(self, "sequential_branch_compact", False)):
                up_pipeline.producer_tail(up_prod_state)
            phase2_pipeline.producer_tail(phase2_prod_state)
        return

    @cute.jit
    def initialize_route_q0_and_publish(self, thread_info, route_inputs, route_outputs, routing_state, task_queue, resident_barriers, shared_addresses, launch_params: DynamicLaunchParams):
        tidx, bidz, gdim_z, warp_idx, is_cta_leader = thread_info
        a_input, topk_ids, topk_weights, input_global_scale = route_inputs
        packed_a_storage, scale_storage, scatter_output, token_map, token_weights = route_outputs
        expert_write_rows, expert_tile_base, pair_head = routing_state
        task_head, task_tail, task_expert, task_valid_rows = task_queue
        barrier_count, barrier_epoch = resident_barriers
        ctrl_base_addr, route_phys_rows_addr, route_expert_ids_addr, q0_input_stage_base_addr, q0_bulk_barrier_addr = shared_addresses
        num_tokens = Int32(a_input.shape[0])
        cols = Int32(a_input.shape[1])
        scatter_base = scatter_output.iterator.toint()
        row_counts = launch_params.row_counts
        num_experts = Int32(row_counts.shape[0])
        sf_blocks_per_row = cols // Int32(16)
        output_bytes_per_row = cols // Int32(2)
        cols_u32 = cols  # FP32 scatter, including the whole zeroed output plane
        scatter_output_u32 = cute.recast_tensor(scatter_output, cutlass.Uint32)
        total_pairs = Int32(topk_ids.shape[0])
        num_topk = total_pairs // num_tokens
        flat_tid = Int32(bidz) * Int32(self.threads_per_cta) + Int32(tidx)
        flat_stride = Int32(gdim_z) * Int32(self.threads_per_cta)
        num_k_tiles = (cols + Int32(63)) // Int32(64)
        route_gate_tile_cnt = launch_params.gate_tile_cnt
        task_slice_chunk = Int32(_TASK_SLICE_CHUNK)
        if num_tokens <= Int32(2048):
            task_slice_chunk = Int32(2)
        i = flat_tid
        while i < num_experts:
            row_counts[i] = Int32(0)
            expert_write_rows[i] = Int32(0)
            i += flat_stride
        if flat_tid < num_experts + Int32(1):
            expert_tile_base[flat_tid] = Int32(0)
        scatter_total_u32 = num_tokens * cols_u32
        scatter_vecs = scatter_total_u32 // Int32(4)
        zero_u32 = Uint32(0)
        zv = flat_tid
        while zv < scatter_vecs:
            st_global_v4_u32(scatter_base + Int64(zv) * Int64(16), zero_u32, zero_u32, zero_u32, zero_u32)
            zv += flat_stride
        j = scatter_vecs * Int32(4) + flat_tid
        while j < scatter_total_u32:
            scatter_output_u32[j // cols_u32, j % cols_u32] = Uint32(0)
            j += flat_stride
        if flat_tid == Int32(0):
            pair_head[Int32(0)] = Int32(0)
            task_head[Int32(0)] = Int32(0)
            task_tail[Int32(0)] = Int32(0)
        cute.arch.sync_threads()
        self.resident_grid_barrier(barrier_count, barrier_epoch, Int32(gdim_z), is_cta_leader)
        route_hist_addr = route_expert_ids_addr + Int32((self.num_mma_warps + 1) * 32 * 4)
        hist_bin = tidx
        while hist_bin < num_experts:
            st_shared_i32(route_hist_addr + hist_bin * Int32(4), Int32(0))
            hist_bin += Int32((self.num_mma_warps + 1) * 32)
        cute.arch.sync_threads()
        hist_idx = flat_tid
        while hist_idx < total_pairs:
            expert_id = topk_ids[hist_idx].to(Int32)
            atomic_add_shared_i32(route_hist_addr + expert_id * Int32(4), Int32(1))
            hist_idx += flat_stride
        cute.arch.sync_threads()
        hist_bin = tidx
        while hist_bin < num_experts:
            subtotal = ld_shared_i32_relaxed(route_hist_addr + hist_bin * Int32(4))
            if subtotal > Int32(0):
                atomic_add_global_i32(get_ptr_as_int64(row_counts, hist_bin), subtotal)
            hist_bin += Int32((self.num_mma_warps + 1) * 32)
        self.resident_grid_barrier(barrier_count, barrier_epoch, Int32(gdim_z), is_cta_leader)
        if num_experts == Int32(256) and bidz == Int32(0) and (warp_idx < Int32(self.num_mma_warps)):
            prefix_lane = Int32(tidx) & Int32(31)
            rows = row_counts[tidx]
            tile_count = (rows + Int32(self.tile_shape_mnk[0]) - Int32(1)) // Int32(self.tile_shape_mnk[0])
            warp_inclusive = tile_count
            for scan_stage in cutlass.range_constexpr(5):
                scan_offset = Int32(1 << scan_stage)
                scan_value = cute.arch.shuffle_sync(warp_inclusive, prefix_lane - Int32(scan_offset))
                if prefix_lane >= Int32(scan_offset):
                    warp_inclusive += scan_value
            warp_exclusive = warp_inclusive - tile_count
            if prefix_lane == Int32(31):
                st_shared_i32(route_hist_addr + warp_idx * Int32(4), warp_inclusive)
            self.epilog_sync_barrier.arrive_and_wait()
            if warp_idx == Int32(0):
                warp_total = Int32(0)
                if prefix_lane < Int32(self.num_mma_warps):
                    warp_total = ld_shared_i32_relaxed(route_hist_addr + prefix_lane * Int32(4))
                warp_sum_inclusive = warp_total
                for scan_stage in cutlass.range_constexpr(5):
                    scan_offset = Int32(1 << scan_stage)
                    scan_value = cute.arch.shuffle_sync(warp_sum_inclusive, prefix_lane - Int32(scan_offset))
                    if prefix_lane >= Int32(scan_offset):
                        warp_sum_inclusive += scan_value
                if prefix_lane < Int32(self.num_mma_warps):
                    st_shared_i32(route_hist_addr + prefix_lane * Int32(4), warp_sum_inclusive - warp_total)
                if prefix_lane == Int32(self.num_mma_warps - 1):
                    _st_shared_i32(ctrl_base_addr + Int32(0), warp_sum_inclusive)
            self.epilog_sync_barrier.arrive_and_wait()
            warp_base = ld_shared_i32_relaxed(route_hist_addr + warp_idx * Int32(4))
            expert_tile_base[tidx] = warp_base + warp_exclusive
            if tidx == Int32(0):
                expert_tile_base[num_experts] = _ld_shared_i32(ctrl_base_addr + Int32(0))
        elif num_experts != Int32(256) and flat_tid == Int32(0):
            tile_acc = Int32(0)
            expert_idx = Int32(0)
            while expert_idx < num_experts:
                expert_tile_base[expert_idx] = tile_acc
                rows = row_counts[expert_idx]
                tile_acc += (rows + Int32(self.tile_shape_mnk[0]) - Int32(1)) // Int32(self.tile_shape_mnk[0])
                expert_idx += Int32(1)
            expert_tile_base[num_experts] = tile_acc
        self.resident_grid_barrier(barrier_count, barrier_epoch, Int32(gdim_z), is_cta_leader)
        expert_scales_addr = route_hist_addr
        route_scales_addr = route_expert_ids_addr
        if tidx < num_experts:
            gs_value = input_global_scale[tidx].to(cutlass.Float32)
            if self.input_scales_are_reciprocal and gs_value != cutlass.Float32(0.0):
                if self.fast_math:
                    gs_value = rcp_approx_ftz(gs_value)
                else:
                    gs_value = cutlass.Float32(1.0) / gs_value
            st_shared_f32(expert_scales_addr + tidx * Int32(4), gs_value)
        if tidx == Int32(0):
            q0_bulk_barrier_init(q0_bulk_barrier_addr)
        cute.arch.sync_threads()
        lane_id = Int32(tidx) & Int32(31)
        _num_cta_warps = Int32(self.num_mma_warps + 1)
        producer_batch_tokens = Int32(self.tile_shape_mnk[0] * self.tile_shape_mnk[1]) // cols
        if producer_batch_tokens > Int32(self.num_mma_warps):
            producer_batch_tokens = Int32(self.num_mma_warps)
        pair_idx = Int32(0)
        expert_id = Int32(0)
        token_idx = Int32(0)
        weight = cutlass.Float32(0.0)
        row = Int32(0)
        phys_row = Int32(0)
        produce_active = Int32(1)
        q0_bulk_phase = Int32(0)
        while produce_active > Int32(0):
            batch_base = Int32(0)
            if is_cta_leader > Int32(0):
                claim_count = producer_batch_tokens
                batch_base = atomic_add_global_i32(get_ptr_as_int64(pair_head, Int32(0)), claim_count)
                _st_shared_i32(ctrl_base_addr + Int32(28), batch_base)
            cute.arch.sync_threads()
            batch_base = _ld_shared_i32(ctrl_base_addr + Int32(28))
            producer_limit = num_tokens
            if batch_base >= producer_limit:
                produce_active = Int32(0)
            else:
                staged_tokens = num_tokens - batch_base
                if staged_tokens > producer_batch_tokens:
                    staged_tokens = producer_batch_tokens
                first_copy_tokens = staged_tokens
                if first_copy_tokens > Int32(4):
                    first_copy_tokens = Int32(4)
                second_copy_tokens = staged_tokens - first_copy_tokens
                first_copy_bytes = first_copy_tokens * cols * Int32(2)
                second_copy_bytes = second_copy_tokens * cols * Int32(2)
                if warp_idx == Int32(self.num_mma_warps):
                    if lane_id == Int32(0):
                        input_batch_addr = Int64(a_input.iterator.toint()) + Int64(batch_base) * Int64(cols) * Int64(2)
                        if first_copy_bytes > Int32(0):
                            q0_cp_async_bulk(q0_input_stage_base_addr, input_batch_addr, first_copy_bytes, q0_bulk_barrier_addr)
                        if second_copy_bytes > Int32(0):
                            q0_cp_async_bulk(q0_input_stage_base_addr + Int32(4) * cols * Int32(2), input_batch_addr + Int64(4) * Int64(cols) * Int64(2), second_copy_bytes, q0_bulk_barrier_addr)
                        q0_bulk_arrive_expect_tx(q0_bulk_barrier_addr, first_copy_bytes + second_copy_bytes)
                token_idx = batch_base + warp_idx
                if warp_idx < producer_batch_tokens and token_idx < num_tokens:
                    route_slot_base = warp_idx * Int32(32)
                    if lane_id == Int32(0):
                        topk_slot = Int32(0)
                        local_topk = Int32(0)
                        producer_first_gs = cutlass.Float32(0.0)
                        producer_scales_equal = Int32(1)
                        while topk_slot < num_topk:
                            pair_idx = token_idx * num_topk + topk_slot
                            expert_id = topk_ids[pair_idx].to(Int32)
                            weight = topk_weights[pair_idx].to(cutlass.Float32)
                            row = atomic_add_global_i32(get_ptr_as_int64(expert_write_rows, expert_id), Int32(1))
                            phys_row = expert_tile_base[expert_id] * Int32(self.tile_shape_mnk[0]) + row
                            st_global_i32(get_ptr_as_int64(token_map, phys_row), token_idx)
                            st_global_f32(get_ptr_as_int64(token_weights, phys_row), weight)
                            route_slot = route_slot_base + local_topk
                            _st_shared_i32(route_phys_rows_addr + route_slot * Int32(4), phys_row)
                            route_scale_row_base = Int32((Uint32(phys_row) >> Uint32(6)) * Uint32(num_k_tiles * Int32(512)) + (Uint32(phys_row) & Uint32(31)) * Uint32(16) + (Uint32(phys_row) >> Uint32(5) & Uint32(1)) * Uint32(4))
                            _st_shared_i32(route_phys_rows_addr + (route_slot + Int32(8)) * Int32(4), route_scale_row_base)
                            selected_scale_bits = _ld_shared_i32(expert_scales_addr + expert_id * Int32(4))
                            _st_shared_i32(route_scales_addr + route_slot * Int32(4), selected_scale_bits)
                            selected_gs = Uint32(selected_scale_bits).bitcast(cutlass.Float32)
                            if local_topk == Int32(0):
                                producer_first_gs = selected_gs
                            elif selected_gs != producer_first_gs:
                                producer_scales_equal = Int32(0)
                            local_topk += Int32(1)
                            topk_slot += Int32(1)
                        _st_shared_i32(route_expert_ids_addr + (route_slot_base + Int32(31)) * Int32(4), local_topk | producer_scales_equal << Int32(4))
                    cute.arch.sync_warp()
                    q0_ready = q0_bulk_try_wait(q0_bulk_barrier_addr, q0_bulk_phase)
                    while q0_ready == Int32(0):
                        q0_ready = q0_bulk_try_wait(q0_bulk_barrier_addr, q0_bulk_phase)
                    route_state = _ld_shared_i32(route_expert_ids_addr + (route_slot_base + Int32(31)) * Int32(4))
                    local_topk = route_state & Int32(15)
                    if local_topk > Int32(0):
                        first_gs = Uint32(_ld_shared_i32(route_scales_addr + route_slot_base * Int32(4))).bitcast(cutlass.Float32)
                        route_scales_equal = route_state >> Int32(4)
                        sf_idx = lane_id
                        while sf_idx < sf_blocks_per_row:
                            block_start = sf_idx * Int32(16)
                            loaded_values = load_shared_bf16x16_to_f32x16(q0_input_stage_base_addr + warp_idx * cols * Int32(2) + block_start * Int32(2))
                            values = cute.make_rmem_tensor((16,), cutlass.Float32)
                            block_max = cutlass.Float32(0.0)
                            for elem_idx in cutlass.range_constexpr(16):
                                value = loaded_values[elem_idx]
                                values[elem_idx] = value
                                block_max = fmax_f32(block_max, fabs_f32(value))
                            if route_scales_equal > Int32(0):
                                gs_value = first_gs
                                packed64 = Uint64(0)
                                scale_byte = Uint8(0)
                                if self.fast_math:
                                    packed64, scale_byte = quantize_block_fp4_fast(values, block_max, gs_value)
                                else:
                                    packed64, scale_byte = quantize_block_fp4(values, block_max, gs_value)
                                cache_slot = Int32(0)
                                while cache_slot < local_topk:
                                    route_slot = route_slot_base + cache_slot
                                    phys_row = _ld_shared_i32(route_phys_rows_addr + route_slot * Int32(4))
                                    output_offset = phys_row * output_bytes_per_row + sf_idx * Int32(8)
                                    st_global_u64(get_ptr_as_int64(packed_a_storage, output_offset), packed64)
                                    scale_row_base = _ld_shared_i32(route_phys_rows_addr + (route_slot + Int32(8)) * Int32(4))
                                    scale_offset = Int32(Uint32(scale_row_base) + (Uint32(sf_idx) >> Uint32(2)) * Uint32(512) + (Uint32(sf_idx) & Uint32(3)))
                                    scale_storage[scale_offset] = scale_byte
                                    cache_slot += Int32(1)
                            else:
                                cache_slot = Int32(0)
                                while cache_slot < local_topk:
                                    route_slot = route_slot_base + cache_slot
                                    phys_row = _ld_shared_i32(route_phys_rows_addr + route_slot * Int32(4))
                                    gs_value = Uint32(_ld_shared_i32(route_scales_addr + route_slot * Int32(4))).bitcast(cutlass.Float32)
                                    packed64 = Uint64(0)
                                    scale_byte = Uint8(0)
                                    if self.fast_math:
                                        packed64, scale_byte = quantize_block_fp4_fast(values, block_max, gs_value)
                                    else:
                                        packed64, scale_byte = quantize_block_fp4(values, block_max, gs_value)
                                    output_offset = phys_row * output_bytes_per_row + sf_idx * Int32(8)
                                    st_global_u64(get_ptr_as_int64(packed_a_storage, output_offset), packed64)
                                    scale_row_base = _ld_shared_i32(route_phys_rows_addr + (route_slot + Int32(8)) * Int32(4))
                                    scale_offset = Int32(Uint32(scale_row_base) + (Uint32(sf_idx) >> Uint32(2)) * Uint32(512) + (Uint32(sf_idx) & Uint32(3)))
                                    scale_storage[scale_offset] = scale_byte
                                    cache_slot += Int32(1)
                            sf_idx += Int32(32)
                q0_bulk_phase = Int32(1) - q0_bulk_phase
        cute.arch.sync_threads()
        _threadfence()
        cute.arch.sync_threads()
        self.resident_grid_barrier(barrier_count, barrier_epoch, Int32(gdim_z), is_cta_leader)
        total_m_tiles = expert_tile_base[num_experts]
        split_groups = (route_gate_tile_cnt + Int32(1)) // Int32(2)
        extra_per_split = split_groups - Int32(1)
        split_tile_count = Int32(0)
        if extra_per_split > Int32(0):
            if num_tokens > Int32(256):
                if num_tokens <= Int32(4096):
                    target_task_count = Int32(4) * Int32(gdim_z)
                    if num_tokens > Int32(2048):
                        target_task_count = (Int32(125) * Int32(gdim_z) + Int32(31)) // Int32(32)
                    missing_tasks = target_task_count - total_m_tiles
                    if missing_tasks > Int32(0):
                        split_tile_count = (missing_tasks + extra_per_split - Int32(1)) // extra_per_split
                        if split_tile_count > total_m_tiles:
                            split_tile_count = total_m_tiles
        if is_cta_leader > Int32(0):
            expert_flush = Int32(bidz)
            while expert_flush < num_experts:
                rows_remaining = row_counts[expert_flush]
                m_tile_offset = Int32(0)
                while rows_remaining > Int32(0):
                    valid_rows = rows_remaining
                    if valid_rows > Int32(self.tile_shape_mnk[0]):
                        valid_rows = Int32(self.tile_shape_mnk[0])
                    if num_tokens <= Int32(256):
                        self.publish_uniform_deferred_tasks(task_expert, task_valid_rows, route_gate_tile_cnt, task_slice_chunk, expert_flush, expert_tile_base[expert_flush] + m_tile_offset, valid_rows)
                    elif num_tokens <= Int32(4096):
                        self.publish_variable_deferred_tasks(task_expert, task_valid_rows, route_gate_tile_cnt, split_tile_count, expert_flush, expert_tile_base[expert_flush] + m_tile_offset, valid_rows)
                    else:
                        self.publish_uniform_deferred_tasks(task_expert, task_valid_rows, route_gate_tile_cnt, task_slice_chunk, expert_flush, expert_tile_base[expert_flush] + m_tile_offset, valid_rows)
                    rows_remaining -= Int32(self.tile_shape_mnk[0])
                    m_tile_offset += Int32(1)
                expert_flush += Int32(gdim_z)
        if flat_tid == Int32(0):
            uniform_groups = (route_gate_tile_cnt + task_slice_chunk - Int32(1)) // task_slice_chunk
            published_task_count = expert_tile_base[num_experts] * uniform_groups
            if num_tokens > Int32(256):
                if num_tokens <= Int32(4096):
                    published_task_count = expert_tile_base[num_experts] + split_tile_count * extra_per_split
            st_global_i32(get_ptr_as_int64(task_tail, Int32(0)), published_task_count)
        self.resident_grid_barrier(barrier_count, barrier_epoch, Int32(gdim_z), is_cta_leader)

    @cute.jit
    def quantize_q1_sC_to_sA_sSFA(
        self,
        tidx,
        valid_rows: Int32,
        task_expert_idx: Int32,
        global_scale: cute.Tensor,
        sC: cute.Tensor,
        sA: cute.Tensor,
        fc1_tRS_sD: cute.Tensor,
        sfa_base_addr: Int32,
        sfa_stage_elements: Int32,
        q1_a_stage_idx: Int32,
        defer_a: Int32,
        deferred_a_words: cute.Tensor,
        q1_sfa_stage_idx: Int32,
        defer_sfa: Int32,
        deferred_sfa_words: cute.Tensor,
        deferred_sfa_slot: Int32,
        epi_rest_m,
    ):
        # Q1 runs exactly once after both N64 halves.  sA remains
        # the full N128 activation consumed by one FC2/scatter pass.
        sA_u8 = cute.recast_tensor(sA[None, None, q1_a_stage_idx], cutlass.Uint8)
        packed_cols = Int32(self.tile_shape_mnk[2] // 2)
        sf_blocks_per_row = Int32(self.tile_shape_mnk[2] // 16)
        gs_value = global_scale[task_expert_idx].to(cutlass.Float32)
        if self.input_scales_are_reciprocal and gs_value != cutlass.Float32(0.0):
            if self.fast_math:
                gs_value = rcp_approx_ftz(gs_value)
            else:
                gs_value = cutlass.Float32(1.0) / gs_value

        deferred_slot = Int32(0)
        for epi_m in cutlass.range_constexpr(epi_rest_m):
            epi_m_valid = valid_rows - Int32(epi_m) * Int32(self.epi_tile[0])
            gated_epi_buffer = Int32(epi_m) % cute.size(fc1_tRS_sD, mode=[3])
            if epi_m_valid > Int32(0):
                rows_offset = Int32(epi_m) * Int32(self.epi_tile[0])
                epi_rows = epi_m_valid
                if epi_rows > Int32(self.epi_tile[0]):
                    epi_rows = Int32(self.epi_tile[0])
                if epi_rows < Int32(0):
                    epi_rows = Int32(0)
                quant_idx = Int32(tidx)
                while quant_idx < epi_rows * sf_blocks_per_row:
                    local_row = quant_idx // sf_blocks_per_row
                    row = rows_offset + local_row
                    sf_block = quant_idx - local_row * sf_blocks_per_row
                    block_start = sf_block * Int32(16)

                    # A BF16x16 quantization block is two aligned N8
                    # segments in K_SW128.  Apply the same explicit swizzle
                    # transform as scatter, then replace sixteen LDS.U16 with
                    # two LDS.128 while preserving element/absmax order.
                    sc_element_offset_lo = Int32(
                        sC.layout(
                            (
                                local_row,
                                block_start,
                                gated_epi_buffer,
                            )
                        )
                    )
                    sc_element_offset_lo = sc_element_offset_lo ^ (
                        (sc_element_offset_lo & Int32(0x1C0)) >> Int32(3)
                    )
                    sc_element_offset_hi = Int32(
                        sC.layout(
                            (
                                local_row,
                                block_start + Int32(8),
                                gated_epi_buffer,
                            )
                        )
                    )
                    sc_element_offset_hi = sc_element_offset_hi ^ (
                        (sc_element_offset_hi & Int32(0x1C0)) >> Int32(3)
                    )
                    sc_smem_addr_lo = get_smem_ptr_as_int32(
                        sC,
                        sc_element_offset_lo,
                    )
                    sc_smem_addr_hi = get_smem_ptr_as_int32(
                        sC,
                        sc_element_offset_hi,
                    )
                    loaded_lo = load_shared_bf16x8_to_f32x8(sc_smem_addr_lo)
                    loaded_hi = load_shared_bf16x8_to_f32x8(sc_smem_addr_hi)
                    values = cute.make_rmem_tensor((16,), cutlass.Float32)
                    block_max = cutlass.Float32(0.0)
                    for elem_idx in cutlass.range_constexpr(8):
                        value = loaded_lo[elem_idx]
                        values[elem_idx] = value
                        block_max = fmax_f32(block_max, fabs_f32(value))
                    for elem_idx in cutlass.range_constexpr(8):
                        value = loaded_hi[elem_idx]
                        values[elem_idx + 8] = value
                        block_max = fmax_f32(block_max, fabs_f32(value))

                    packed64 = Uint64(0)
                    scale_byte = Uint8(0)
                    if self.fast_math:
                        packed64, scale_byte = quantize_block_fp4_fast(
                            values, block_max, gs_value
                        )
                    else:
                        packed64, scale_byte = quantize_block_fp4(
                            values, block_max, gs_value
                        )
                    packed_base = sf_block << Int32(3)
                    dst_pcol = row & Int32(63)
                    xor_bits = ((dst_pcol >> Int32(1)) & Int32(0x3)) << Int32(4)
                    row_high = row >> Int32(6)
                    if defer_a > Int32(0):
                        deferred_a_words[deferred_slot * Int32(2)] = Uint32(
                            packed64 & Uint64(0xFFFFFFFF)
                        )
                        deferred_a_words[deferred_slot * Int32(2) + Int32(1)] = Uint32(
                            packed64 >> Uint64(32)
                        )
                    else:
                        for byte_idx in cutlass.range_constexpr(8):
                            src_pcol = packed_base + Int32(byte_idx)
                            dst_row = src_pcol ^ xor_bits
                            dst_flat = dst_row * packed_cols + dst_pcol
                            byte_val = Uint8(
                                (packed64 >> Uint64(byte_idx * 8)) & Uint64(0xFF)
                            )
                            sA_u8[dst_flat] = byte_val

                    outer_m_idx = row % Int32(32)
                    inner_m_idx = row // Int32(32)
                    inner_k_idx = sf_block % Int32(4)
                    k_tile_idx = sf_block // Int32(4)
                    sf_raw_idx = (
                        k_tile_idx * Int32(32 * 4 * 4)
                        + outer_m_idx * Int32(4 * 4)
                        + inner_m_idx * Int32(4)
                        + inner_k_idx
                    )
                    if defer_sfa > Int32(0):
                        deferred_sfa_words[deferred_sfa_slot] = deferred_sfa_words[
                            deferred_sfa_slot
                        ] | (Uint32(scale_byte) << Uint32(deferred_slot * Int32(8)))
                    else:
                        st_shared_u8(
                            sfa_base_addr
                            + q1_sfa_stage_idx * sfa_stage_elements
                            + sf_raw_idx,
                            scale_byte,
                        )
                    deferred_slot += Int32(1)
                    quant_idx += Int32(self.num_mma_warps * self.num_threads_per_warp)
        return

    @cute.jit
    def flush_deferred_q1_a(
        self,
        tidx,
        valid_rows: Int32,
        deferred_a_words: cute.Tensor,
        sA: cute.Tensor,
        q1_a_stage_idx: Int32,
    ):
        sA_u8 = cute.recast_tensor(sA[None, None, q1_a_stage_idx], cutlass.Uint8)
        packed_cols = Int32(self.tile_shape_mnk[2] // 2)
        sf_blocks_per_row = Int32(self.tile_shape_mnk[2] // 16)
        deferred_slot = Int32(0)
        quant_idx = Int32(tidx)
        while quant_idx < valid_rows * sf_blocks_per_row:
            row = quant_idx // sf_blocks_per_row
            sf_block = quant_idx - row * sf_blocks_per_row
            packed64 = Uint64(deferred_a_words[deferred_slot * Int32(2)]) | (
                Uint64(deferred_a_words[deferred_slot * Int32(2) + Int32(1)])
                << Uint64(32)
            )
            packed_base = sf_block << Int32(3)
            dst_pcol = row & Int32(63)
            xor_bits = ((dst_pcol >> Int32(1)) & Int32(0x3)) << Int32(4)
            row_high = row >> Int32(6)
            for byte_idx in cutlass.range_constexpr(8):
                src_pcol = packed_base + Int32(byte_idx)
                dst_row = src_pcol ^ xor_bits
                dst_flat = dst_row * packed_cols + dst_pcol
                sA_u8[dst_flat] = Uint8(
                    (packed64 >> Uint64(byte_idx * 8)) & Uint64(0xFF)
                )
            deferred_slot += Int32(1)
            quant_idx += Int32(self.num_mma_warps * self.num_threads_per_warp)
