"""Reproduce the static M64 descriptor/Q0 fork from pinned M128 sources.

M64 keeps one physical 128-row SFA atom per logical 64-row tile and uses
its lower half. Q1's immediate and deferred byte stores also use the M64
flattened-coordinate stride. The M128 parent and arithmetic stay intact.
"""
import ast
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCES = {
    'moe_dynamic_gated_sf6.py': 'de87e617a3f52370e1bda1656438099c895618247e45a9a64313559e196033bb',
    'moe_dynamic_gated_sf6_q0.py': 'fc62f7e59f660d741c68b1ccb32173055914279c40052e62972b03b881650593',
    '_moe_dynamic/gated.py': 'adf2c7336b785a96d2865fb1aa42d636392845b55ca84c733210d24193ca24ba',
}


def build():
    imports = ['from ._moe_dynamic.gated import load_shared_bf16x8_to_f32x8',
               'from flashinfer.cute_dsl.fp4_common import st_shared_u8, get_smem_ptr_as_int32']
    methods = []
    for name, expected in SOURCES.items():
        source = (ROOT / 'engine/kernels/b12x' / name).read_text()
        if hashlib.sha256(source.encode()).hexdigest() != expected:
            raise ValueError('M64 parent source changed: ' + name)
        tree = ast.parse(source)
        for node in tree.body if not name.startswith('_moe_dynamic/') else ():
            if isinstance(node, (ast.Import, ast.ImportFrom)) and getattr(node, 'module', '') != '__future__':
                segment = ast.get_source_segment(source, node)
                if segment not in imports:
                    imports.append(segment)
        class_name = {'moe_dynamic_gated_sf6.py': 'MoEGatedDynamicKernelSF6',
                      'moe_dynamic_gated_sf6_q0.py': 'MoEGatedDynamicKernelSF6Q0',
                      '_moe_dynamic/gated.py': 'MoEGatedDynamicKernel'}[name]
        cls = next(node for node in tree.body if isinstance(node, ast.ClassDef) and node.name == class_name)
        wanted = {'moe_dynamic_gated_sf6.py': ('__call__', 'kernel'),
                  'moe_dynamic_gated_sf6_q0.py': ('initialize_route_q0_and_publish',),
                  '_moe_dynamic/gated.py': ('quantize_q1_sC_to_sA_sSFA', 'flush_deferred_q1_a')}[name]
        for node in cls.body:
            if isinstance(node, ast.FunctionDef) and node.name in wanted:
                begin = min([node.lineno] + [d.lineno for d in node.decorator_list])
                methods.append('\n'.join(source.splitlines()[begin - 1:node.end_lineno]))
    result = ('# SPDX-License-Identifier: Apache-2.0\n'
              '# Generated by measurements/st_prefill_phase2_20260913/generate_m64_bodies.py.\n'
              '# Static source fork: SFA geometry and Q1 M64 byte coordinates; see generator pins.\n'
              'from __future__ import annotations\n\n' + '\n'.join(imports)
              + '\n\nclass M64Bodies:\n' + '\n\n'.join(methods) + '\n')
    replacements = (
        ('packed_a.shape, self.sf_vec_size',
         '(packed_a.shape[0] * 2, packed_a.shape[1], packed_a.shape[2]), self.sf_vec_size'),
        ('sfa_tensor,\n                self.sfa_smem_layout_staged,\n                (self.tile_shape_mnk[0], self.tile_shape_mnk[2]),',
         'sfa_tensor,\n                self.sfa_smem_layout_staged,\n                (128, self.tile_shape_mnk[2]),'),
        ('mSFA, cute.slice_(self.tile_shape_mnk, (None, 0, None)), (None, None, None)',
         'mSFA, (128, self.tile_shape_mnk[2]), (None, None, None)'),
        ('(Uint32(phys_row) >> Uint32(7)) * Uint32(num_k_tiles * Int32(512))',
         '(Uint32(phys_row) >> Uint32(6)) * Uint32(num_k_tiles * Int32(512))'),
        ('(Uint32(phys_row) >> Uint32(5) & Uint32(3)) * Uint32(4)',
         '(Uint32(phys_row) >> Uint32(5) & Uint32(1)) * Uint32(4)'),
    )
    for before, after in replacements:
        if result.count(before) != 1:
            raise ValueError('M64 source edit is no longer unique: ' + before)
        result = result.replace(before, after)
    # Recast sA's logical shape has 64 M coordinates before the K coordinate.
    # The M128 formula doubles K here; for M64 it aliases neighbouring rows
    # and leaves half of the bytes unwritten. Both Q1 stores must agree.
    before = 'dst_row = ((src_pcol ^ xor_bits) << Int32(1)) + row_high'
    if result.count(before) != 2:
        raise ValueError('expected exactly the immediate and deferred Q1 byte stores')
    result = result.replace(before, 'dst_row = src_pcol ^ xor_bits')
    ast.parse(result)
    return result


if __name__ == '__main__':
    (ROOT / 'engine/kernels/b12x/_prefill_m64_bodies.py').write_text(build())
