"""Reproduce the static M64 descriptor/Q0 fork from pinned M128 sources.

M64 keeps one physical 128-row SFA atom per logical 64-row tile and uses
its lower half. This avoids sharing an atom between independently routed
expert tiles. Packed activations remain compact M64 rows; only SFA is padded.
"""
import ast
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCES = {
    'moe_dynamic_gated_sf6.py': '6efb0a2ec044dfbaeb43af92f569b6c130a99bee751fb5a129f78dac1183300e',
    'moe_dynamic_gated_sf6_q0.py': '759a519145c3edecac42ea917abbd8003b142f02ba4d41f86fc2d58e939a51ba',
}


def build():
    imports, methods = [], []
    for name, expected in SOURCES.items():
        source = (ROOT / 'engine/kernels/b12x' / name).read_text()
        if hashlib.sha256(source.encode()).hexdigest() != expected:
            raise ValueError('M64 parent source changed: ' + name)
        tree = ast.parse(source)
        for node in tree.body:
            if isinstance(node, (ast.Import, ast.ImportFrom)) and getattr(node, 'module', '') != '__future__':
                segment = ast.get_source_segment(source, node)
                if segment not in imports:
                    imports.append(segment)
        cls = next(node for node in tree.body if isinstance(node, ast.ClassDef))
        wanted = ('__call__', 'kernel') if name.endswith('_sf6.py') else ('initialize_route_q0_and_publish',)
        for node in cls.body:
            if isinstance(node, ast.FunctionDef) and node.name in wanted:
                begin = min([node.lineno] + [d.lineno for d in node.decorator_list])
                methods.append('\n'.join(source.splitlines()[begin - 1:node.end_lineno]))
    result = ('# SPDX-License-Identifier: Apache-2.0\n'
              '# Generated by measurements/st_prefill_phase2_20260913/generate_m64_bodies.py.\n'
              '# Static source fork: only SFA geometry/addressing changes; see generator pins.\n'
              'from __future__ import annotations\n\n' + '\n'.join(imports)
              + '\n\nclass M64Bodies:\n' + '\n\n'.join(methods) + '\n')
    replacements = (
        ('packed_a.shape, self.sf_vec_size',
         '(packed_a.shape[0] * 2, packed_a.shape[1], packed_a.shape[2]), self.sf_vec_size'),
        ('sfa_tensor,\n                self.sfa_smem_layout_staged,\n                (self.tile_shape_mnk[0], self.tile_shape_mnk[2]),',
         'sfa_tensor,\n                self.sfa_smem_layout_staged,\n                (128, self.tile_shape_mnk[2]),'),
        ('mSFA, cute.slice_(self.tile_shape_mnk, (None, 0, None)), (None, None, None)',
         'mSFA, (128, self.tile_shape_mnk[2]), (None, None, None)'),
        ('(Uint32(phys_row) >> Uint32(7)) * Uint32(num_k_tiles * Int32(512))',
         '(Uint32(phys_row) >> Uint32(6)) * Uint32(num_k_tiles * Int32(512))'),
        ('(Uint32(phys_row) >> Uint32(5) & Uint32(3)) * Uint32(4)',
         '(Uint32(phys_row) >> Uint32(5) & Uint32(1)) * Uint32(4)'),
    )
    for before, after in replacements:
        if result.count(before) != 1:
            raise ValueError('M64 source edit is no longer unique: ' + before)
        result = result.replace(before, after)
    ast.parse(result)
    return result


if __name__ == '__main__':
    (ROOT / 'engine/kernels/b12x/_prefill_m64_bodies.py').write_text(build())
