"""The served Qwen3.8 vision stack's answers, read inside the served image -- the reference engine/profiles/qwen38/vision.py
is held to (tests/fixtures/qwen38_vision_reference.json), and, with --real, the tower on the checkpoint's weights.

Runs in `vllm/vllm-openai:qwen38-flash-next` (transformers 5.15.1, vLLM's qwen3_vl), CPU only, the repo mounted at /repo
and the checkpoint at /ckpt:

    docker run --rm -e CUDA_VISIBLE_DEVICES= -v $PWD:/repo:ro -v ~/models/qwen38-flash-next-nvfp4:/ckpt:ro \
        -v /tmp/out:/out --entrypoint python3 vllm/vllm-openai:qwen38-flash-next \
        /repo/probes/qwen38_vision_reference.py --ckpt /ckpt --fixture /out/qwen38_vision_reference.json [--real /out/real.json]

What it records:
  * processor: for synthetic pictures of every kind the door must handle (sizes that round, shrink and grow; alpha,
    grayscale, palette; an EXIF-rotated JPEG), the bytes' sha256, then vLLM's loader (ImageMediaIO) and the
    checkpoint's image processor: the grid and the pixel_values' shape, sum and sha256.
  * mrope: vLLM's Qwen3VLForConditionalGeneration._get_mrope_input_positions for prompts with pictures.
  * toy_tower: transformers' Qwen3VLVisionModel on a toy configuration with weights generated by `toy_weights` below
    (the test regenerates them and checks their digest), fp32, one picture -> its output rows. The toy's numbers come
    from integer hashing (`portable`), not a seeded torch generator: torch's stream differs between builds (CI's torch
    drew other weights than the served image's from the same seed).
  * --real: the checkpoint's tower in transformers (fp32, and bf16 -- what bf16 alone costs) against this repo's `Vision`
    (bf16) on two pictures.
  * --precision: where the tower's bf16 error comes from -- this repo's tower with fp32 in one place at a time
    (attention, MLP, merger, the stream between blocks, every block's arithmetic) against the whole tower in fp32 (the
    bf16 weights widened), and the fp32 stream's size block by block (its largest value, its largest channel's share).
"""
from __future__ import annotations

import argparse
import hashlib
import io
import json
import sys
from pathlib import Path
from types import SimpleNamespace

import numpy as np
import torch

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

TOY = dict(depth=2, hidden_size=32, num_heads=2, intermediate_size=48, out_hidden_size=40, patch_size=4, temporal_patch_size=2,
           spatial_merge_size=2, in_channels=3, num_position_embeddings=16, hidden_act="gelu_pytorch_tanh",
           deepstack_visual_indexes=[])
TOY_GRID = (1, 4, 6)


def synthetic(h: int, w: int, seed: int = 0) -> np.ndarray:
    """A deterministic RGB picture with structure at every scale: gradients, a checkerboard, a seeded speckle."""
    yy, xx = np.mgrid[0:h, 0:w]
    rng = np.random.default_rng(seed)
    r = xx * 255 // max(w - 1, 1)
    g = yy * 255 // max(h - 1, 1)
    b = (((xx // 7) + (yy // 5)) % 2) * 200 + rng.integers(0, 56, size=(h, w))
    return np.stack([r, g, b], -1).astype(np.uint8)


def cases() -> "dict[str, bytes]":
    """name -> encoded bytes: the pictures the door's processor must match."""
    from PIL import Image
    out = {}

    def png(img):
        buf = io.BytesIO()
        img.save(buf, format="PNG")
        return buf.getvalue()

    out["rgb_640x480_aligned"] = png(Image.fromarray(synthetic(480, 640, 1)))
    out["rgb_517x333_rounds"] = png(Image.fromarray(synthetic(333, 517, 2)))
    out["rgb_40x30_grows"] = png(Image.fromarray(synthetic(30, 40, 3)))
    out["rgb_5000x4000_shrinks"] = png(Image.fromarray(synthetic(4000, 5000, 4)))
    out["rgb_3000x20_wide"] = png(Image.fromarray(synthetic(20, 3000, 5)))
    rgba = synthetic(200, 300, 6)
    alpha = (np.arange(300)[None, :] * 255 // 299).repeat(200, 0).astype(np.uint8)
    out["rgba_300x200"] = png(Image.fromarray(np.dstack([rgba, alpha]), "RGBA"))
    out["gray_257x129"] = png(Image.fromarray(synthetic(129, 257, 7)[..., 0], "L"))
    pal = Image.fromarray(synthetic(96, 160, 8)).convert("P", palette=Image.Palette.ADAPTIVE, colors=32)
    pal.info["transparency"] = 0
    out["palette_160x96_transparent"] = png(pal)
    jpg = Image.fromarray(synthetic(180, 320, 9))
    exif = Image.Exif()
    exif[0x0112] = 6                                          # orientation: rotate 90 degrees clockwise to view
    buf = io.BytesIO()
    jpg.save(buf, format="JPEG", quality=90, exif=exif)
    out["jpeg_320x180_exif6"] = buf.getvalue()
    return out


def processor_reference(ckpt: Path) -> dict:
    from transformers import AutoImageProcessor
    from vllm.multimodal.media.image import ImageMediaIO
    proc = AutoImageProcessor.from_pretrained(str(ckpt))
    io_ = ImageMediaIO(image_mode="RGB")
    out = {"processor": type(proc).__name__, "cases": {}}
    for name, data in cases().items():
        loaded = io_.load_bytes(data)
        image = getattr(loaded, "media", loaded)
        r = proc(images=[image], return_tensors="pt")
        pv = r["pixel_values"].to(torch.float32).contiguous()
        out["cases"][name] = {"bytes_sha256": hashlib.sha256(data).hexdigest(), "loaded_size": list(image.size),
                              "grid": [int(x) for x in r["image_grid_thw"][0].tolist()], "shape": list(pv.shape),
                              "sum": float(pv.double().sum()), "sha256": hashlib.sha256(pv.numpy().tobytes()).hexdigest()}
    return out


def mrope_reference() -> dict:
    """vLLM's rule on prompts with pictures: text, two pictures with text between, adjacent pictures, a picture first."""
    from vllm.model_executor.models.qwen3_vl import Qwen3VLForConditionalGeneration as Q
    cfg = SimpleNamespace(video_token_id=248057, vision_start_token_id=248053, vision_end_token_id=248054,
                          vision_config=SimpleNamespace(spatial_merge_size=2))
    IMG = 248056

    def feature(offset, grid):
        return SimpleNamespace(modality="image", mm_position=SimpleNamespace(offset=offset, length=grid[1] * grid[2] // 4),
                               data={"image_grid_thw": SimpleNamespace(data=torch.tensor(grid))})

    prompts = {
        "text_image_text": [(5, (1, 8, 12)), 9],                   # 5 text, a 4x6 picture, 9 text
        "two_pictures": [(3, (1, 4, 4)), 2, (0, (1, 6, 10)), 4],   # text, picture, text, picture right after, text
        "picture_first": [(0, (1, 10, 6)), 7],
    }
    out = {}
    for name, spec in prompts.items():
        tokens, feats, media = [], [], []
        for part in spec:
            if isinstance(part, int):
                tokens += [1] * part
                continue
            lead, grid = part
            tokens += [1] * lead
            n = grid[1] * grid[2] // 4
            feats.append(feature(len(tokens), grid))
            media.append({"positions": list(range(len(tokens), len(tokens) + n)), "grid": list(grid)})
            tokens += [IMG] * n
        pos, delta = Q._get_mrope_input_positions(input_tokens=tokens, mm_features=feats, config=cfg)
        pos = torch.as_tensor(np.asarray(pos))
        out[name] = {"length": len(tokens), "media": media, "positions": pos.tolist(), "delta": int(delta)}
    return out


def portable(shape, salt: int) -> torch.Tensor:
    """fp32 values spread about zero (uniform on [-1.7, 1.7), unit-ish spread), the same on every machine and every
    torch: a 64-bit mix of each index and the salt in exact integer arithmetic, its top 53 bits a float64 in [0, 1)."""
    n = int(np.prod(shape))
    with np.errstate(over="ignore"):
        x = (np.arange(n, dtype=np.uint64) + np.uint64(salt) * np.uint64(0x9E3779B97F4A7C15)) \
            * np.uint64(6364136223846793005) + np.uint64(1442695040888963407)
        x ^= x >> np.uint64(33)
        x *= np.uint64(0xFF51AFD7ED558CCD)
        x ^= x >> np.uint64(33)
        x *= np.uint64(0xC4CEB9FE1A85EC53)
        x ^= x >> np.uint64(33)
    u = (x >> np.uint64(11)).astype(np.float64) / float(1 << 53)
    return torch.from_numpy(((u * 2 - 1) * 1.7).astype(np.float32)).reshape(tuple(shape))


def toy_weights(specs, seed: int = 0) -> "dict[str, torch.Tensor]":
    """bf16 weights for the toy tower, deterministic everywhere (`portable`): norms near one, biases and matrices small."""
    out = {}
    for i, s in enumerate(specs):
        t = portable(s.shape, seed * 1000 + i + 1)
        if s.name.endswith((".norm1.weight", ".norm2.weight", "merger.norm.weight")):
            t = 1 + 0.1 * t
        elif s.name.endswith("pos_embed.weight"):
            t = 0.5 * t
        else:
            t = 0.08 * t
        out[s.name] = t.to(torch.bfloat16)
    return out


def digest(weights: "dict[str, torch.Tensor]") -> str:
    h = hashlib.sha256()
    for name in sorted(weights):
        h.update(name.encode())
        h.update(weights[name].view(torch.int16).numpy().tobytes())
    return h.hexdigest()


def toy_facts():
    from engine.profiles.qwen38.vision import VisionFacts
    T = TOY
    return VisionFacts(depth=T["depth"], hidden=T["hidden_size"], heads=T["num_heads"], inter=T["intermediate_size"],
                       out_hidden=T["out_hidden_size"], patch=T["patch_size"], temporal=T["temporal_patch_size"],
                       merge=T["spatial_merge_size"], channels=T["in_channels"], grid_side=4, image_token=9, video_token=8,
                       vision_start=6, vision_end=7, mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5), min_pixels=16, max_pixels=4096)


def toy_pixels() -> torch.Tensor:
    V = toy_facts()
    return portable((V.tokens(TOY_GRID) * V.merge * V.merge, V.patch_dim), 999_999).to(torch.bfloat16)


def hf_tower(config: dict, weights: "dict[str, torch.Tensor]", prefix: str):
    from transformers.models.qwen3_vl.configuration_qwen3_vl import Qwen3VLVisionConfig
    from transformers.models.qwen3_vl.modeling_qwen3_vl import Qwen3VLVisionModel
    cfg = Qwen3VLVisionConfig(**config)
    cfg._attn_implementation = "sdpa"
    model = Qwen3VLVisionModel(cfg).float().eval()
    state = {k[len(prefix):]: v.float() for k, v in weights.items() if k.startswith(prefix)}
    missing, unexpected = model.load_state_dict(state, strict=False)
    missing = [k for k in missing if "rotary" not in k]
    if missing or unexpected:
        raise RuntimeError(f"tower weights: missing {missing[:5]}, unexpected {unexpected[:5]}")
    return model


def toy_reference() -> dict:
    from engine.profiles.qwen38 import vision
    V = toy_facts()
    w = toy_weights(vision.specs(V))
    model = hf_tower(TOY, w, vision.PREFIX)
    with torch.no_grad():
        out = model(toy_pixels().float(), grid_thw=torch.tensor([TOY_GRID]))
    rows = getattr(out, "pooler_output", out).float()
    return {"config": TOY, "grid": list(TOY_GRID), "weights_sha256": digest(w), "rows": rows.tolist()}


def real_comparison(ckpt: Path) -> dict:
    """The checkpoint's tower, transformers fp32 against this repo's bf16 `Vision`, on two pictures (CPU)."""
    from engine.base.checkpoint import Checkpoint
    from engine.profiles.qwen38 import vision
    V = vision.load(ckpt)
    S = vision.specs(V)
    w = {k: v.to(torch.bfloat16) for k, v in Checkpoint(str(ckpt)).load([s.name for s in S]).items()}
    cfg = json.loads((ckpt / "config.json").read_text())["vision_config"]
    model = hf_tower({k: cfg[k] for k in TOY}, w, vision.PREFIX)
    model_bf16 = hf_tower({k: cfg[k] for k in TOY}, w, vision.PREFIX).to(torch.bfloat16)    # the served precision, in transformers
    ours = vision.Vision(V, w)
    door = vision.Door(V)
    out = {}
    for name in ("rgb_640x480_aligned", "rgb_517x333_rounds"):
        item = door.prepare("image", cases()[name])
        pv = vision.pixel_values(V, item["canvas"], item["grid"]).to(torch.bfloat16)
        grid = torch.tensor([item["grid"]])
        with torch.no_grad():
            ref = getattr(model(pv.float(), grid_thw=grid), "pooler_output").float()
            half = getattr(model_bf16(pv, grid_thw=grid), "pooler_output").float()
            got = ours.encode(item["canvas"], item["grid"]).float()

        def against(x, y):
            cos = torch.nn.functional.cosine_similarity(x, y, dim=-1)
            return {"rel_err": round(float((x - y).norm() / y.norm()), 6), "max_abs": round(float((x - y).abs().max()), 5),
                    "row_cos_min": round(float(cos.min()), 6), "row_cos_mean": round(float(cos.mean()), 6)}
        out[name] = {"grid": list(item["grid"]), "tokens": int(ref.shape[0]), "ref_absmax": round(float(ref.abs().max()), 4),
                     "ours_vs_fp32": against(got, ref), "transformers_bf16_vs_fp32": against(half, ref),
                     "ours_vs_transformers_bf16": against(got, half)}
    return out


def precision_breakdown(ckpt: Path) -> dict:
    """The tower's bf16 error taken apart (module docstring, --precision), CPU, two pictures."""
    import torch.nn.functional as Fn
    from engine.base.checkpoint import Checkpoint
    from engine.profiles.qwen38 import vision
    V = vision.load(ckpt)
    S = vision.specs(V)
    tower = vision.Vision(V, {k: v.to(torch.bfloat16) for k, v in Checkpoint(str(ckpt)).load([s.name for s in S]).items()})
    p16 = tower.p
    p32 = {k: v.float() for k, v in p16.items()}
    P, out = vision.PREFIX, {}
    for name in ("rgb_640x480_aligned", "rgb_517x333_rounds"):
        item = vision.Door(V).prepare("image", cases()[name])
        pv = vision.pixel_values(V, item["canvas"], item["grid"]).to(torch.bfloat16)
        pos, cos, sin = tower.tables(item["grid"][1], item["grid"][2])

        def run(attn=False, mlp=False, merger=False, stream=False, every=False, trace=None):
            """fp32 where asked (every: all of it, the bf16 weights widened), bf16 elsewhere, as served."""
            f32 = lambda on: (p32, torch.float32) if on or every else (p16, torch.bfloat16)      # noqa: E731
            pw, dt = f32(False)
            x = Fn.linear(pv.to(dt), pw[P + "patch_embed.proj.weight"].view(V.hidden, -1), pw[P + "patch_embed.proj.bias"])
            x = x + pos.to(dt)
            for i in range(V.depth):
                b, L = f"{P}blocks.{i}.", x.shape[0]
                pa, da = f32(attn)
                h = Fn.layer_norm(x.to(da), (V.hidden,), pa[b + "norm1.weight"], pa[b + "norm1.bias"], vision.LN_EPS)
                q, k, v = Fn.linear(h, pa[b + "attn.qkv.weight"], pa[b + "attn.qkv.bias"]).view(L, 3, V.heads, V.head_dim).unbind(1)
                q, k = tower._rope(q, cos, sin), tower._rope(k, cos, sin)
                heads = lambda z: z.transpose(0, 1).unsqueeze(0)                                   # noqa: E731
                a = Fn.scaled_dot_product_attention(heads(q), heads(k), heads(v), scale=V.head_dim ** -0.5)
                a = Fn.linear(a.squeeze(0).transpose(0, 1).reshape(L, V.hidden), pa[b + "attn.proj.weight"], pa[b + "attn.proj.bias"])
                x = (x.float() + a.float()) if stream or every else x + a.to(x.dtype)
                pm, dm = f32(mlp)
                h = Fn.layer_norm(x.to(dm), (V.hidden,), pm[b + "norm2.weight"], pm[b + "norm2.bias"], vision.LN_EPS)
                h = Fn.gelu(Fn.linear(h, pm[b + "mlp.linear_fc1.weight"], pm[b + "mlp.linear_fc1.bias"]), approximate="tanh")
                h = Fn.linear(h, pm[b + "mlp.linear_fc2.weight"], pm[b + "mlp.linear_fc2.bias"])
                x = (x.float() + h.float()) if stream or every else (x + h.to(x.dtype)).to(torch.bfloat16)
                if trace is not None:
                    trace.append(x.float())
            pg, dg = f32(merger)
            y = Fn.layer_norm(x.to(dg), (V.hidden,), pg[P + "merger.norm.weight"], pg[P + "merger.norm.bias"], vision.LN_EPS)
            y = Fn.gelu(Fn.linear(y.reshape(-1, 4 * V.hidden), pg[P + "merger.linear_fc1.weight"], pg[P + "merger.linear_fc1.bias"]))
            return Fn.linear(y, pg[P + "merger.linear_fc2.weight"], pg[P + "merger.linear_fc2.bias"]).float()

        with torch.no_grad():
            stream_ref, stream_bf = [], []
            ref = run(every=True, trace=stream_ref)
            arms = {"all bf16 (served)": run(trace=stream_bf), "attention fp32": run(attn=True), "mlp fp32": run(mlp=True),
                    "merger fp32": run(merger=True), "stream fp32": run(stream=True),
                    "every block's arithmetic fp32 (stream bf16)": run(attn=True, mlp=True, merger=True)}

        def rel(a, b):
            return round(float((a - b).norm() / b.norm()), 5)
        out[name] = {"tokens": int(ref.shape[0]),
                     "arms": {k: {"rel_err": rel(v, ref), "row_cos_mean": round(float(Fn.cosine_similarity(v, ref, dim=-1).mean()), 6)}
                              for k, v in arms.items()},
                     "stream": [{"after_block": i, "bf16_rel_err": rel(b, r), "absmax": round(float(r.abs().max()), 1),
                                 "top_channel_share": round(float(r.pow(2).sum(0).max() / r.pow(2).sum()), 4)}
                                for i, (b, r) in enumerate(zip(stream_bf, stream_ref))]}
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--ckpt", type=Path, required=True)
    ap.add_argument("--fixture", type=Path)
    ap.add_argument("--real", type=Path)
    ap.add_argument("--precision", type=Path)
    a = ap.parse_args()
    torch.set_num_threads(max(1, torch.get_num_threads()))
    if a.fixture:
        ref = {"source": "vllm/vllm-openai:qwen38-flash-next (transformers 5.15.1) via probes/qwen38_vision_reference.py",
               "torch": torch.__version__, "preprocessor_config": json.loads((a.ckpt / "preprocessor_config.json").read_text()),
               "processor": processor_reference(a.ckpt), "mrope": mrope_reference(), "toy_tower": toy_reference()}
        import torchvision
        import PIL
        ref["torchvision"], ref["pil"] = torchvision.__version__, PIL.__version__
        a.fixture.write_text(json.dumps(ref, indent=1) + "\n")
        print(f"wrote {a.fixture}")
    if a.precision:
        rep = precision_breakdown(a.ckpt)
        a.precision.write_text(json.dumps(rep, indent=1) + "\n")
        print(json.dumps({k: v["arms"] for k, v in rep.items()}, indent=1))
    if a.real:
        rep = real_comparison(a.ckpt)
        a.real.write_text(json.dumps(rep, indent=1) + "\n")
        print(json.dumps(rep, indent=1))


if __name__ == "__main__":
    main()
