#!/usr/bin/env python3
"""Does the guarded b12x dynamic kernel treat an unrouted slot as nothing?

GPU probe; run inside the qwen38-fi618 image with qwen38_b12x mounted:

    python3 probes/qwen38_b12x_guard.py [E K N TOPK T]      (default: the Qwen3.8 shape)

Three checks on synthetic NVFP4 weights, one B12xMoEWrapper, serving geometry
(use_cuda_graph=True, workspace at T):

  1. every slot -1            -> runs, output all zero, finite
  2. 75 % of slots -1 (a TEP=4 rank's share) vs the same routing with those
     slots kept valid at weight 0 -> outputs bit-identical
  3. a token with no routed slot -> its output row is zero

It refuses to run on an unguarded kernel: the stock one faults (or worse,
does not) on check 1, and a pass there would mean nothing.
"""

import os
import sys

import torch


def main() -> int:
    from flashinfer import fp4_quantize
    from flashinfer.cute_dsl.utils import convert_sf_to_mma_layout
    from flashinfer.fused_moe.cute_dsl import b12x_moe
    from flashinfer.fused_moe.cute_dsl.blackwell_sm12x._moe_dynamic import generic

    head = open(generic.__file__, encoding="utf-8").read(400)
    if "GENERATED by tools/qwen38_b12x_guard_gen.py" not in head:
        print(f"REFUSED: {generic.__file__} is the stock kernel, not the guarded "
              f"override; mount overlay/modules/qwen38_b12x first")
        return 2

    E, K, N, TOPK, T = (int(a) for a in (sys.argv[1:6] or (512, 2560, 640, 10, 2048)))
    dev = "cuda"
    g = torch.Generator(device=dev).manual_seed(int(os.environ.get("SEED", "7")))

    def quant_stack(rows, cols):
        qs, sfs = [], []
        for _ in range(E):
            w = (torch.randn(rows, cols, device=dev, generator=g) * 0.02).to(torch.bfloat16)
            gs = ((448.0 * 6.0) / w.abs().amax().float().clamp(min=1e-6)).reshape(1)
            q, sf = fp4_quantize(w, gs, sf_vec_size=16, is_sf_swizzled_layout=False)
            qs.append(q.view(torch.uint8))
            sfs.append(sf.reshape(rows, cols // 16))
        q, sf = torch.stack(qs), torch.stack(sfs)
        return q, convert_sf_to_mma_layout(sf.reshape(E * rows, cols // 16), m=rows, k=cols, num_groups=E)

    w1, w1_sf = quant_stack(2 * N, K)
    w2, w2_sf = quant_stack(K, N)
    ones = torch.ones(E, device=dev, dtype=torch.float32)
    wrap = b12x_moe.B12xMoEWrapper(num_experts=E, top_k=TOPK, hidden_size=K, intermediate_size=N,
                                   use_cuda_graph=True, max_num_tokens=T, num_local_experts=E,
                                   activation="silu")
    x = (torch.randn(T, K, device=dev, generator=g) * 0.5).to(torch.bfloat16)
    ids = torch.stack([torch.randperm(E, device=dev, generator=g)[:TOPK] for _ in range(T)]).to(torch.int32)
    wts = torch.rand(T, TOPK, device=dev, generator=g).float()
    wts = wts / wts.sum(-1, keepdim=True)

    def run(i, s):
        out = wrap.run(x=x, w1_weight=w1, w1_weight_sf=w1_sf, w2_weight=w2, w2_weight_sf=w2_sf,
                       token_selected_experts=i.contiguous(), token_final_scales=s.contiguous(),
                       w1_alpha=ones, w2_alpha=ones, fc2_input_scale=ones)
        torch.cuda.synchronize()
        return out

    bad = 0
    # 1. everything unrouted
    out = run(torch.full_like(ids, -1), wts)
    ok = bool(torch.isfinite(out.float()).all()) and bool((out == 0).all())
    print(f"  all -1        : finite={bool(torch.isfinite(out.float()).all())} all_zero={bool((out == 0).all())}  {'OK' if ok else 'FAIL'}")
    bad += not ok
    # 2./3. a TEP=4 rank's share unrouted, token 0 fully unrouted
    mask = torch.rand(T, TOPK, device=dev, generator=g) < 0.75
    mask[0] = True
    ref = run(ids, torch.where(mask, torch.zeros_like(wts), wts))
    out = run(torch.where(mask, torch.full_like(ids, -1), ids), wts)
    same = torch.equal(out, ref)
    diff = float((out.float() - ref.float()).abs().max())
    tok0 = bool((out[0] == 0).all())
    nz = bool((ref.float().abs().sum(-1) > 0).float().mean() > 0.5)   # the reference is not itself all zero
    print(f"  75% unrouted  : unrouted={int(mask.sum())}/{mask.numel()} bit_identical={same} max|diff|={diff} "
          f"reference_nontrivial={nz}  {'OK' if same and nz else 'FAIL'}")
    print(f"  no-route token: row0_zero={tok0}  {'OK' if tok0 else 'FAIL'}")
    bad += (not same) + (not nz) + (not tok0)
    print(f"{'PASS' if not bad else 'FAIL'} qwen38 b12x guard E={E} K={K} N={N} topk={TOPK} T={T}")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
