#!/usr/bin/env python3
"""What is already inside the ST image, so nobody spends a day rebuilding it.

`engine/kernels/SOURCES.json` records what we brought IN. Nothing recorded what was already THERE, and on
2026-09-12 that cost a day: a sortless top-k/top-p sampler kernel was written by hand and merged before anyone
noticed `flashinfer.sampling.top_k_top_p_sampling_from_probs` was in the image and 1.4-1.8x faster.

    python3 tools/inventory.py                                  # against the newest st-engine image
    python3 tools/inventory.py --image st-engine:prod-abceb6a0
    python3 tools/inventory.py --write                           # refresh engine/INVENTORY.md

Reads only; it starts a container to run `python3 -c "import ..."` and nothing else. It does not ask for a GPU,
because production GLM-5.3 is this engine and a process that takes the GPU beside it can get the server killed.
"""
from __future__ import annotations

import argparse
import pathlib
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
# Listed by name, because these are the ones somebody is about to write a kernel for.
MODULES = ["flashinfer.sampling", "flashinfer.norm", "flashinfer.activation", "flashinfer.fused_moe",
           "flashinfer.gemm", "flashinfer.page", "flashinfer.decode", "flashinfer.prefill",
           "deep_gemm", "xgrammar"]
# Listed by version only: present, but too wide to read and not where our kernels live.
VERSIONS = ["torch", "triton", "transformers", "tokenizers", "safetensors", "numpy", "einops",
            "sentencepiece", "cutlass", "nvtx", "outlines", "flash_attn"]
PROBE = '''
import importlib, importlib.metadata as md


def version(top):
    try:
        return md.version(top)
    except Exception:
        try:
            return getattr(importlib.import_module(top), "__version__", "?")
        except Exception:
            return "?"


for name in {versions!r}:
    try:
        importlib.import_module(name)
    except Exception as exc:
        print(f"-- {{name}}: not in this image ({{type(exc).__name__}})")
        continue
    print(f"-- {{name}} {{version(name)}}")
print()
for name in {modules!r}:
    try:
        m = importlib.import_module(name)
    except Exception as exc:
        print(f"!! {{name}} {{type(exc).__name__}}")
        continue
    names = sorted(n for n in dir(m) if not n.startswith("_") and callable(getattr(m, n, None))
                   and getattr(m, n).__module__.split(".")[0] == name.split(".")[0])
    print(f"## {{name}} {{version(name.split('.')[0])}}")
    for n in names:
        print(f"   {{n}}")
'''


def newest_image() -> str:
    out = subprocess.run(["docker", "images", "--format", "{{.Repository}}:{{.Tag}}"],
                         capture_output=True, text=True).stdout.split()
    images = [i for i in out if i.startswith("st-engine:")]
    if not images:
        raise SystemExit("no st-engine image on this host: pass --image")
    return images[0]


def read(image: str) -> str:
    probe = PROBE.format(modules=MODULES, versions=VERSIONS)
    p = subprocess.run(["docker", "run", "--rm", "--entrypoint", "python3", image, "-c", probe],
                       capture_output=True, text=True, timeout=600)
    if p.returncode:
        raise SystemExit(f"could not read {image}:\n{p.stderr[-2000:]}")
    return p.stdout


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--image", default=None)
    ap.add_argument("--write", action="store_true", help="refresh the generated half of engine/INVENTORY.md")
    ap.add_argument("--grep", default=None, help="only names containing this")
    a = ap.parse_args()
    image = a.image or newest_image()
    body = read(image)
    if a.grep:
        keep, module = [], ""
        for line in body.splitlines():
            if line.startswith("##"):
                module = line
            elif a.grep in line:
                if module:
                    keep.append(module); module = ""
                keep.append(line)
        body = "\n".join(keep)
    if not a.write:
        print(f"# {image}\n{body}")
        return 0
    doc = ROOT / "engine" / "INVENTORY.md"
    text = doc.read_text()
    mark = "<!-- generated by tools/inventory.py -->"
    head = text.split(mark)[0]
    doc.write_text(f"{head}{mark}\n\n```\n# {image}\n{body.rstrip()}\n```\n")
    print(f"  wrote {doc} from {image}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
